### ISSUE TITLE
Build vvenc in colab python

### ISSUE THREAD

**Issue by mkherchouche** [fraunhoferhhi/vvenc#110]
I am trying to create the statically linked release version of the encoder applications in the install/bin/release-static/ subdirectory.
Using this command:  !make install-release
This is the result:
cmake -S . -B build/release-static  -DCMAKE_BUILD_TYPE=Release
CMake Error: The source directory "/content/vvenc/build/release-static" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:192: recipe for target 'build/release-static' failed
make: *** [build/release-static] Error 1

How can i fix it please ?

**Comment by adamjw24** [comment]
Did you create the directory build/release-static?

**Comment by mkherchouche** [comment]
By using the apropriate version of cmake i solved the problem. thanks
