### ISSUE TITLE
Y4M support inside of VVenC

### ISSUE THREAD

**Issue by sgmihai** [fraunhoferhhi/vvenc#113]
Reopening this issue as it's important for the people wanting to use this encoder, myself included.
"Hello. I've been trying out VVenC recently, and I've noticed that this encoder doesn't support y4m input for some reason."

Negative energy is not a reason for closing the issue, as it's still not resolved.

As for the negative energy and whoever reported me for harrasment, perhaps my knowledge of vvc is incomplete, I thought this was h266 patent protected codec, and thus for profit/corporate. Well, whatever the case, I meant no harrassment, and  you sir/madam are a little too butthurt to report for trvial things like this.

**Comment by adamjw24** [comment]
No negative energy, yet calling me "butthurt". Reporting this again. You are welcome to contribute your time and energy this issue thought.

**Comment by sgmihai** [comment]
Butthurt - mental distress or irritation caused by an overreaction to a perceived personal slight, a bad outcome, etc.
This is how I perceived it.
Why are you so keen on making reports, what purpose does it serve ? It seems you are the one with the negative energy to me.

**Comment by n00mkrad** [comment]
Closing an issue for "negative energy" and then still adding it.

Yeah, you guys are funny.

https://github.com/fraunhoferhhi/vvenc/commit/0d34873d40d85b2e09b611dd0185562fbaa8b731
