### ISSUE TITLE
vvencapp --version no longer works

### ISSUE THREAD

**Issue by Orum** [fraunhoferhhi/vvenc#118]
Running `vvencapp --version` on 1.3.0 no longer gives any output, and simply exits with an exit status of 1.  `vvencFFapp --version` does work, however.

**Comment by adamjw24** [comment]
Indeed. Thanks for reporting, we'll have a look

**Comment by Orum** [comment]
Thanks for the fix in 1.3.1.  I now see the version string, but it reports the incorrect version (1.3.1 claims it is 1.3.0).

**Comment by adamjw24** [comment]
Of course it says 1.3.0, since we forgot to update the version...

I updated it and re-tagged. It's not a best practice, but I hope bcs of the weekend not so many people pulled it yet. Otherwise using -f should do the trick.
