### ISSUE TITLE
Compilation w/ GCC 10.2.1 failed

### ISSUE THREAD

**Issue by 1div0** [fraunhoferhhi/vvenc#12]
[ 52%] Building CXX object source/Lib/vvenc/CMakeFiles/vvenc.dir/EncoderIf.cpp.o
/1TB/usr/src/github.com/1div0/vvenc/source/Lib/EncoderLib/EncCu.cpp: In member function ‘void vvenc::EncCu::xCheckRDCostAffineMerge(vvenc::CodingStructure*&, vvenc::CodingStructure*&, vvenc::Partitioner&, const vvenc::EncTestMode&)’:
/1TB/usr/src/github.com/1div0/vvenc/source/Lib/EncoderLib/EncCu.cpp:3543:44: error: ‘candCostList’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 3543 |       double ThesholdCost = MRG_FAST_RATIO * candCostList[0];
/1TB/usr/src/github.com/1div0/vvenc/source/Lib/EncoderLib/EncCu.cpp:3543:44: error: ‘candCostList’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1plus: all warnings being treated as errors
make[2]: *** [source/Lib/vvenc/CMakeFiles/vvenc.dir/build.make:706: source/Lib/vvenc/CMakeFiles/vvenc.dir/__/EncoderLib/EncCu.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:176: source/Lib/vvenc/CMakeFiles/vvenc.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

gcc version 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC)

**Comment by Jamaika1** [comment]
```
CommonDef.h:600:55: warning: ignoring attributes on template argument 'void(int, const char*, va_list)' {aka 'void(int, const char*, char*)'} [-Wignored-attributes]
  600 | extern std::function<void( int, const char*, va_list )> g_msgFnc;
      |                                                       ^
```

**Comment by adamjw24** [comment]
For now it seems that GCC-10 is still very fresh and sometimes oversensitive to some issues. For some of the issues, workarounds more than actual fixes are required and we don't really want to be putting that in. We'll see how the situation develops as the VVenC code develops and GCC-10 matures and maybe reevaluate fixing this at some later point.

For now please consider using some older version of GCC.
