### ISSUE TITLE
Visual studio 2015

### ISSUE THREAD

**Issue by Jatin6999** [fraunhoferhhi/vvenc#120]
So I have cloned the entire project. What should be my next step? Please help me
![issue1](https://user-images.githubusercontent.com/58022972/146084049-3a314619-f1d8-452c-8cdb-074d8a0f4ea8.png)

**Comment by Jatin6999** [comment]
![issue2](https://user-images.githubusercontent.com/58022972/146086990-f268d1c1-bec3-47a6-a318-51763ed748e1.png)

**Comment by Jatin6999** [comment]
![issue3](https://user-images.githubusercontent.com/58022972/146087067-67fe3e35-5b95-4daf-8020-3fc5df993a15.png)

**Comment by 1480c1** [comment]
Never mind, I realized you said vs2015,

According to README.md
> In order to compile the software for Windows, Visual Studio 15 2017 or higher and cmake version 3.13 or higher are required

Not sure if I can help, I don't have any visual studios install on any of my systems.

**Comment by Jatin6999** [comment]
![issue4](https://user-images.githubusercontent.com/58022972/146098443-af6b15d8-0793-4fd6-933f-438fd5db34d4.png)

**Comment by Jatin6999** [comment]
![soln1](https://user-images.githubusercontent.com/58022972/146098539-dc007955-ac91-48e0-81b5-745ec2086f1a.png)

**Comment by Jatin6999** [comment]
I think I got it to run. Not sure how to proceed with this. Kindly help me with this.

**Comment by 1480c1** [comment]
You might want to look at https://github.com/fraunhoferhhi/vvenc#how-to-use-vvenc and at the example command line
```bash
vvencapp --preset medium -i BUS_176x144_75@15.yuv -s 176x144 -o str.266
```

or if you want to use y4m inputs https://github.com/fraunhoferhhi/vvenc/discussions/116

**Comment by Jatin6999** [comment]
I'm sorry, but I need a bit of spoon feeding. Whenever I run something I'm not able to type any command. Where exactly is the terminal?

**Comment by Jatin6999** [comment]
![Uploading soln2.png…]()

**Comment by Jatin6999** [comment]
![soln2](https://user-images.githubusercontent.com/58022972/146169694-f51829cb-956b-4c24-9072-66bc8a1e0c5f.png)

**Comment by adamjw24** [comment]
> I'm sorry, but I need a bit of spoon feeding. Whenever I run something I'm not able to type any command. Where exactly is the terminal?

Open the start menu, and type in "cmd", hit enter and you are in the console.

To use VVenC, plaese build it in the x64-Release configuration (can be configured in the dropdown menu on top).

**Comment by ItamarOliveira** [comment]
Well, you may call it "spoon feeding", or "baby steps orientation". We live odd times, any orientation is a incentive and support.
I do remember times when we must change BIOS configuration of IRQ or DMA to try to make something work. Without any online resources, just few magazines.
Do you believe we should have a fixed topic like "read me first"?

Let me know if I can help with any subject.

Itamar Oliveira
+ 55 21 98123 2023
+ 55 24 99988 9399

"Carl Sagan, tinha uma declaração muito bonita que adaptei para minha saudação pessoal, por favor perdoe minha falta de habilidade.
"Considerando a vastidão do tempo e do espaço, é um privilégio poder dividir com vocês o mesmo planeta e a mesma época"."

"Carl Sagan had a very beautiful declaration that I adapted to my personal greeting, please forgive my lack of  ability.
"Considering the vastness of time and space, it is a privilege to be able to share with you the same planet and the same time"."


________________________________

**Comment by ItamarOliveira** [comment]
🤓

Itamar Oliveira
+ 55 21 98123 2023
+ 55 24 99988 9399

"Carl Sagan, tinha uma declaração muito bonita que adaptei para minha saudação pessoal, por favor perdoe minha falta de habilidade.
"Considerando a vastidão do tempo e do espaço, é um privilégio poder dividir com vocês o mesmo planeta e a mesma época"."

"Carl Sagan had a very beautiful declaration that I adapted to my personal greeting, please forgive my lack of  ability.
"Considering the vastness of time and space, it is a privilege to be able to share with you the same planet and the same time"."


________________________________

**Comment by Jatin6999** [comment]
> > I'm sorry, but I need a bit of spoon feeding. Whenever I run something I'm not able to type any command. Where exactly is the terminal?
> 
> Open the start menu, and type in "cmd", hit enter and you are in the console.
> 
> To use VVenC, plaese build it in the x64-Release configuration (can be configured in the dropdown menu on top where it now says x64-Debug in your screenshot).

![soln3](https://user-images.githubusercontent.com/58022972/146221143-13146fba-0666-4d70-a7bc-0c0c78ad3397.png)

**Comment by Jatin6999** [comment]
Where to find "x64-Release"?

**Comment by Jatin6999** [comment]
I think I got it
![soln4](https://user-images.githubusercontent.com/58022972/146222489-6134efbd-570b-49ac-a4dd-04c406860019.png)

**Comment by adamjw24** [comment]
I see, this looks different if you use the CMake project.

Exactly, press the green + and add x64-Release configuration. After than you will be able to select it.

**Comment by Jatin6999** [comment]
![soln5](https://user-images.githubusercontent.com/58022972/146224603-fff2491f-a082-472f-bd1c-4e2a39506bfc.png)

**Comment by adamjw24** [comment]
It seems you manage to build the project. Can this issue be closed?

Thanks for the help explaining it.

**Comment by Jatin6999** [comment]
I still haven't figured out how to give an input. Can you please tell me where or which file has got the video that you have used for testing?

**Comment by adamjw24** [comment]
We have private files for testing that cannot be shared.

You can download sample videos for experimenting from e.g. https://media.xiph.org/video/derf

Mind that the Xiph videos are in Y4M format, while VVenC requires raw YUV input. Have a look at https://github.com/fraunhoferhhi/vvenc/discussions/116 for examples of how to deal with that. You'll need working FFmpeg installation for that.

You can see some sample encoder command lines in the test definition section of the CMakeLists.txt: https://github.com/fraunhoferhhi/vvenc/blob/a4cd29cfdf4e5fd38e2993b0ce4876583f212729/CMakeLists.txt#L294-L361

The video we ship for testing is not suitable any other purposes, so please don't use it.

**Comment by Jatin6999** [comment]
Okay, I really appreciate all the help that you are giving me.
As you can see "vvenc Project" in VS
![soln7](https://user-images.githubusercontent.com/58022972/146424165-cfd705ed-2bfc-48ab-92e8-7e6f6bc448dc.png)

**Comment by Jatin6999** [comment]
I cannot see it in my system
![soln8](https://user-images.githubusercontent.com/58022972/146424398-599c87ec-37ae-4470-b2e3-d6896e475c96.png)

**Comment by adamjw24** [comment]
I can. In the `out` directory.

**Comment by Jatin6999** [comment]
![IMG_0965](https://user-images.githubusercontent.com/58022972/146608046-9e08c92d-6182-4ee1-8687-196dfa043b7b.jpg)

**Comment by Jatin6999** [comment]
How do I proceed?

**Comment by adamjw24** [comment]
Just follow the `README.md` or the whitepaper (can be found on the wiki page). You are in the wrong directory. For Linux, it is really easy to build the project.

```sh
git clone git@github.com:fraunhoferhhi/vvenc.git
cd vvenc
make install-release
cd ..
```

After which all the files you need will be in the `vvenc/install/` directory.

Just be sure to install all the necessary packages. It at least includes: `cmake`, `g++` and `git`. Not sure right now if theres anything else.

**Comment by Jatin6999** [comment]
Can you please give me the list of commands that I can use?
I want the whole command 
For example: vvencapp --preset medium -i BUS_176x144_75@15.yuv -s 176x144 -o str.266

I was able to run this one.
And I want to obtain the rate-distortion curve.
How do I obtain the graph? Any suggestions?

**Comment by adamjw24** [comment]
This goes beyound the scope of support we can give here. Please have a look at the great online resources out there, e.g. https://ottverse.com/what-is-bd-rate-bd-psnr-calculation-interpretation/

I'm closing the issue for now.

Best, Adam
