### ISSUE TITLE
Enable tile/slice parallelism and -qpa will cause mismatch between reconstructed YUV and decoded YUV.

### ISSUE THREAD

**Issue by 9reyson** [fraunhoferhhi/vvenc#121]
--preset fast -qpa 1 -f 33 -t -1 -s 960x540 -fr 30 --EnablePicPartitioning 1 --TileColumnWidthArray 10  --qp 28 -o rec.yuv  -b str.bin -i input.yuv

**Comment by 9reyson** [comment]
VVenC version: v1.3.0

**Comment by adamjw24** [comment]
Indeed. Thanks for reporting. We'll provide a fix soon.
