### ISSUE TITLE
y4m input gets error at few last frames.

### ISSUE THREAD

**Issue by ZenKiyoshi** [fraunhoferhhi/vvenc#129]
My system: Windows, vvenc 1.3.1 (the latest master with y4m supported)

When I use --y4m input, I always get error near the end, just few last frames to finish encoding.

My command and my cases I have tested (8bit, 10bit)

**ffmpeg**
`ffmpeg -i "11sec_video.mkv" -pix_fmt yuv420p10le -f rawvideo - | vvencapp -i - -s 1920x1080 --fps 24000/1001 --preset faster -c yuv420_10 -q 23 -o "f-rawvideo-10b.266" `
no error

`ffmpeg -i "11sec_video.mkv" -pix_fmt yuv420p10le -f yuv4mpegpipe -strict -1 - | vvencapp -i - --y4m --preset faster -c yuv420_10 -q 23 -o "f-yuv4mpegpipe-10b.266"`
got error

`ffmpeg -i "11sec_video.mkv" -f yuv4mpegpipe - | vvencapp -i - --y4m --preset faster -q 23 -o "f-yuv4mpegpipe-8b.266"`
got error
![f-yuv4mpegpipe-10b](https://user-images.githubusercontent.com/98955073/152474265-55b25bdc-45b3-4d8c-bd80-911131668e8d.png)

**vspipe**
the script files vs00.vpy are same, for 10bit output I insert `clip = core.fmtc.bitdepth(clip, bits=10)`

`vspipe vs00.vpy - | vvencapp -i - -s 1920x1080 --fps 24000/1001 --preset faster -q 23 -o "vspipe-8b-no-y4m.266"`
`vspipe vs00.vpy - | vvencapp -i - -s 1920x1080 --fps 24000/1001 --preset faster -q 23 -c yuv420_10 -o "vspipe-10b-no-y4m.266"`
no error

`vspipe vs00.vpy - --y4m | vvencapp -i - --y4m --preset faster -q 23 -o "vspipe-8b-WITH-Y4M.266"`
`vspipe vs00.vpy - --y4m | vvencapp -i - --y4m --preset faster -q 23 -c yuv420_10 -o "vspipe-10b-WITH-Y4M.266"`
got error
![vspipe-10b-WITH-Y4M](https://user-images.githubusercontent.com/98955073/152474314-a93e1563-5a0f-4d08-93e7-edeac8821978.png)

All encoded files are watchable via command
**vvdecapp -b tos.266 --y4m -o - | mpv -**
but those files which error has occurred are lack of few last frames.

My encoded file and log: https://drive.google.com/drive/folders/1Fry0BM6oPSIsUIgmT18tIJ4QwuNaD2Ni?usp=sharing

**Comment by adamjw24** [comment]
Please check after the bugfix and let us know.

**Comment by ZenKiyoshi** [comment]
The bug has been fixed.
