### ISSUE TITLE
internal-bitdepth 8 not working

### ISSUE THREAD

**Issue by Alex080900** [fraunhoferhhi/vvenc#13]
8bit does not work with preset slow, slower but does work with preset faster, fast and medium.

vvencapp -i input.yuv -s 1920x1080 -c yuv420 -r 30 -o slower.266 --preset slower -ip 256 --qp 32 --internal-bitdepth 8

CODING TOOL CFG: IBD:0 CIP:0 SAO:1 ALF:1 (NonLinLuma:1 NonLinChr:1) CCALF:1 WPP:0 WPP-Substreams:1 TMVP:1 DQ:1 (Thr: 4) SDH:0 CST:1 BDOF:1 DMVR:1 MTSImplicit:0 SBT:1 JCbCr:1 CabacInitPresent:1 AMVR:1 SMVD:1 LMCS:1 (Signal:SDR Opt:0) CIIP:1 MIP:1 AFFINE:1 (PROF:1, Type:1)MMVD:1 DisFracMMVD:1 SbTMVP:1 GPM:1 LFNST:1 MTS:1 (IntraCand:3)ISP:1 TS:2 TSLog2MaxSize:3 useChromaTS:0 BDPCM:1 
ENC. ALG. CFG: QPA:2 HAD:1 RDQ:1 RDQTS:1 ASR:1 MinSearchWindow:96 RestrictMESampling:0 EDO:2 MCTF:2 [L:0, T:0] 
FAST TOOL CFG: ECU:0 FEN:1 FDM:1 ESD:0 FastSearch:1 LCTUFast:1 FastMrg:1 PBIntraFast:1 AMaxBT:1 FastQtBtEnc:1 ContentBasedFastQtbt:0 FastMIP:0 FastLocalDualTree:1 FastSubPel:0 QtbttExtraFast:0 
RATE CONTROL CFG: RateControl:0 
PARALLEL PROCESSING CFG: FPP:0 NumFppThreads:-1 FppBitEqual:0 WPP:4 WppBitEqual:1 WF:0
VVEnc info: Fraunhofer VVC Encoder ver. 0.2.0.0 

terminate called after throwing an instance of 'vvenc::Exception'
  what():  
ERROR: In function "xT" in /home/user/git/vvenc-0.2.0.0/source/Lib/CommonLib/TrQuant.cpp:506: Negative shift
Aborted (core dumped)

**Comment by adamjw24** [comment]
We found the bug and will push the fix shortly.
