### ISSUE TITLE
Negative number shift in EncReshape::calcSeqStats

### ISSUE THREAD

**Issue by chenm001** [fraunhoferhhi/vvenc#136]
average = average / (double)(1 << (m_lumaBD - 10));
      variance = variance / (double)(1 << (2 * (m_lumaBD - 10)));
      binIdx = (uint32_t)((pxlY >> (m_lumaBD - 10)) / binLen);

when input and internal bitDepth setting to 8, the count of shift  will be negative number (8-10)=-2
Is it a bug?

**Comment by adamjw24** [comment]
Looks like it. We have this code from an old version of VTM, I see they already fixed this error. We'll probably port their fix. Thanks for reporting.
