### ISSUE TITLE
Crash by encoding Y4M input file

### ISSUE THREAD

**Issue by 1div0** [fraunhoferhhi/vvenc#142]
ffmpeg -start_number 180100 -i ${INPUT_PATH}/midnight_sun/midnight_sun_%06d.exr -vf scale=1920:1080 -framerate 50/1 -time_base 1/50 -strict -1 -pix_fmt yuv420p10 -color_primaries bt2020 -colorspace bt2020_ncl -color_trc bt2020-10 -y ${OUTPUT_PATH}/midnight_sun.1080p50.y4m

vvencapp --input /1TB/Video/Y4M/midnight_sun.1080p50.y4m --qp 32 --hdr hlg_2020 --decodedpicturehash 1 --output /1TB/Video/VVC/midnight_sun.1080p50.HLG.266

Segmentation fault occurs always, last output string is:
**vvencapp [error]: read file failed: Source image does not contain valid y4m header (FRAME)**

Thread 5 "vvencapp" received signal SIGSEGV, Segmentation fault.

Gathering more relevant information such as backtrace...

**Comment by ZenKiyoshi** [comment]
Try latest master.

I use to have issue with y4m input: https://github.com/fraunhoferhhi/vvenc/issues/129, and it has been fixed.

**Comment by 1div0** [comment]
Thank you so much.

Results at https://vvc.reflexion.tv/

Closing.
