### ISSUE TITLE
I cannot encode when using this tool

### ISSUE THREAD

**Issue by georgesaumen** [fraunhoferhhi/vvenc#145]
Hello,

I have used your tool to encode my videos to H266 codec but I dont know my command is wrong or I build fail, I cannot run a command and if they can run and they finish, the final file is just 1kb and cannot open.

This is my command I have used: vvencFFapp --InputFile test.mp4 -s 1920x1012 --InternalBitDepth 10 -fr 24 -t 8 --TargetBitrate 9500 -b demo123456.mp4

Can u give me a guide how to encode using this ?

Thanks!

![1234589](https://user-images.githubusercontent.com/86090065/157820327-273c791c-ee16-467f-a74d-b755d18ab2a3.png)

![Untitled](https://user-images.githubusercontent.com/86090065/157820136-7df210be-b6d5-4346-ac9a-b7813ca41059.png)

**Comment by adamjw24** [comment]
Please mind that the encoder can only deal with RAW YUV files, i.e. you cannot feed it an mp4 as input. Please see https://github.com/fraunhoferhhi/vvenc/discussions/116 on how to deal with arbitrary input formats using a workaround. For your use-case, you'd need to do first and second pass as separate calls (`--Pass 1` and `--Pass 2`, and keep all other params the same), because the script does not support 2-pass encoding as a single call.

**Comment by georgesaumen** [comment]
thanks

Vào Th 6, 11 thg 3, 2022 lúc 14:59 Adam Wieckowski ***@***.***>
đã viết:

**Comment by lehmann-c** [comment]
Furthermore you have to define the bitrate in bits/second.
You set '--TargetBitrate 9500' which is 9,5kbit/second.

**Comment by georgesaumen** [comment]
> Furthermore you have to define the bitrate in bits/second. You set '--TargetBitrate 9500' which is 9,5kbit/second.

So what value I set if i want 9500 bits/second ?

**Comment by georgesaumen** [comment]
> Please mind that the encoder can only deal with RAW YUV files, i.e. you cannot feed it an mp4 as input. Please see #116 on how to deal with arbitrary input formats using a workaround. For your use-case, you'd need to do first and second pass as separate calls (`--Pass 1` and `--Pass 2`, and keep all other params the same), because the script does not support 2-pass encoding as a single call.

Hi, thanks for your support, can i ask after I finish encoded pass 1, in pass 2 i use a .266 file i have encoded in pass 1 as input on pass 2 or use original Y4M file ?

**Comment by georgesaumen** [comment]
And can I ask they encode finish when they reached at a target bitrate we have set ?

![Untitled](https://user-images.githubusercontent.com/86090065/157855081-efd1f63b-270d-4a98-94bb-d40cd765fd27.png)

**Comment by lehmann-c** [comment]
> > Furthermore you have to define the bitrate in bits/second. You set '--TargetBitrate 9500' which is 9,5kbit/second.
> 
> So what value I set if i want 9500 bits/second ?

I don´t think you want to encode with a bitrate of 9500 bits/second (which is 9,5 kbit/s).
Just for comparison: audio needs a bitrate of at least 64 kbit/s (64000 bits/sec).
You should at least use 0,5 Mbit/sec which is 500000 bits/second.

**Comment by lehmann-c** [comment]
> Hi, thanks for your support, can i ask after I finish encoded pass 1, in pass 2 i use a .266 file i have encoded in pass 1 as input on pass 2 or use original Y4M file ?

You always have to use the Y4M as input.
The first pass don´t write a bitstream file. At least the .266 file from the first pass should have a filesize of 0.

But when you are using the vvencapp/vvencFFapp with a target bitrate (as written in your fist statement), the 2 passes are executed automatically. Means after running the first pass, the second pass runs automatically internally and you don´t have to run the 2 passes individually.
So either:
 vvencFFapp --InputFile in.yuv -s 1920x1012 --InternalBitDepth 10 -fr 24 -t 8 --TargetBitrate 1000000 -b out.266
Or manually:
 vvencFFapp --InputFile in.y4m -t 8 --TargetBitrate 1000000  --NumPasses 2 --Pass 1 --RCStatsFile statsfile.json -b out.266
 vvencFFapp --InputFile in.4ym -t 8 --TargetBitrate 1000000  --NumPasses 2 --Pass 2 --RCStatsFile statsfile.json -b out.266

**Comment by georgesaumen** [comment]
Thanks, but do u have any other way to create Y4M raw video file ? Because
I create with ffmpeg the size is so big and my hard drive doesn't have
enough space to hold files

Vào Th 2, 14 thg 3, 2022 lúc 16:20 Christian Lehmann <
***@***.***> đã viết:

**Comment by adamjw24** [comment]
See #116, it does the transcoding with a pipe, so the whole video is never decoded to RAW at once, only the frames being encoded.

**Comment by georgesaumen** [comment]
Thanks!

Vào Th 2, 14 thg 3, 2022 lúc 16:31 Adam Wieckowski ***@***.***>
đã viết:
