### ISSUE TITLE
Encoding Problem With 8K Video

### ISSUE THREAD

**Issue by wpss929** [fraunhoferhhi/vvenc#152]
I met some problems when I tried to use VVenC for a 8K 420 YUV file encoding.

Firstly I followed readme.md to build vvencapp.exe under Visual Studio 2019, then I tried to use it for encoding under command

`vencapp -i scene.yuv -s 7680x4320 —fps 24 -f 12 -o vvc.bin`

scene.yuv is from a 8K 24 fps yuv file, and I cut it to 12 frames for quick test on my old computer :(

Then I use VVdeC to decode bin file under the command
`vvdecapp -b vvc.bin -o rec_vvc.yuv`

However when It finished, I found reconstructed yuv file is obviously bigger than original file(1.11GB vs 569MB), and ffplay showed that the yuv file is made of wrong pictures(green and warping)

Then I tried vvFFenc and it showed same problem ( bigger file and wrong yuv ) so I wonder why this happened and how to solve it?

**Comment by adamjw24** [comment]
VVenC always uses 10bit as internal bit depth.

Please have a look at: https://github.com/fraunhoferhhi/vvdec/issues/4
