### ISSUE TITLE
Seeking for VFW release

### ISSUE THREAD

**Issue by WinkeyCheng** [fraunhoferhhi/vvenc#156]
I wanna ask has H.266vfw codec been released? How can I obtain or how to build it?
Also, I tried to build this git using MakeFile in Ubuntu 20.04 server,
it just stuck in 34% and the system killed the process

**Comment by adamjw24** [comment]
What do you mean with H.266vfw? I don't know what its supposed to be.

Strange about your Ubuntu server build. Could you post some more information and logs?

**Comment by WinkeyCheng** [comment]
vfw means Video For Windows
I just want to ask if there is a release for windows users
For the Ubuntu server build, the problem has resolved by upgrading the server's hardware, 2GB RAM isn't enough to build this massive work.

**Comment by adamjw24** [comment]
I see.

VVenC supports Windows mostly without issues, you can download the sources, compile it and use without problems.

We do not, and do not plan to, provide binary distributions for any platforms though.
