### ISSUE TITLE
Will vvenc support Cutree like x265?

### ISSUE THREAD

**Issue by idxa** [fraunhoferhhi/vvenc#163]

**Comment by adamjw24** [comment]
Eventually, yes.

There is also the block importance mapping alg. from VTM, which reuses the results of temporal filtering, so its less heavy. Otherwise it tries to get gain based on the same principles.

We will eventually look into those, but would also appreciate help on this very much.

**Comment by BlueSwordM** [comment]
Cutree is just temporal RDO, and last I checked, VVenC already has support for that.
