### ISSUE TITLE
Build error when using Visual Studio 17 2022

### ISSUE THREAD

**Issue by georgesaumen** [fraunhoferhhi/vvenc#164]
Hello,

I got this error when build a vvenc:

My command: cmake -B build -DCMAKE_BUILD_TYPE=Release 
                        cmake -S . -B build/release-shared -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=1

![Untitled](https://user-images.githubusercontent.com/86090065/170952330-dba71eee-6713-4117-aed3-87f5ad17f369.png)

Can i have a solution for this ?

Thanks!

**Comment by adamjw24** [comment]
Please specify the exact command you used to try to build the project. Looks like you don't have any compiler in the path, but will need more info.

**Comment by adamjw24** [comment]
Also, what system is that? WSL, some kind of cygwin?

**Comment by adamjw24** [comment]
Why would you specify `-DCMAKE_INSTALL_PREFIX=/usr/local` for a MSVC build?

Please run `cmake.exe` and see if the MSVC 17 2022 generator is correctly listed.

**Comment by georgesaumen** [comment]
> Why would you specify `-DCMAKE_INSTALL_PREFIX=/usr/local` for a MSVC build?
> 
> Please run `cmake.exe` and see if the MSVC 17 2022 generator is correctly listed.

I use  -DCMAKE_INSTALL_PREFIX=/usr/local because I do like a build wiki in your github (https://github.com/fraunhoferhhi/vvenc/wiki/Build) . I use windows 11 and this is a terminal of windows 11

**Comment by georgesaumen** [comment]
![Untitled](https://user-images.githubusercontent.com/86090065/170954884-7377af5e-745d-4a58-81f3-77a45862b916.png)

**Comment by adamjw24** [comment]
> > Why would you specify `-DCMAKE_INSTALL_PREFIX=/usr/local` for a MSVC build?
> > Please run `cmake.exe` and see if the MSVC 17 2022 generator is correctly listed.
> 
> I use -DCMAKE_INSTALL_PREFIX=/usr/local because I do like a build wiki in your github (https://github.com/fraunhoferhhi/vvenc/wiki/Build) . I use windows 11 and this is a terminal of windows 11

Point taken. Still, the path does not exist on your computer, because it's a windows. Either skip this part or use an existing path.

**Comment by adamjw24** [comment]
Please post full logs including clone+cd+mkdir+your cmake call+output.
