### ISSUE TITLE
Is vvenc only under win32?

### ISSUE THREAD

**Issue by Jamaika1** [fraunhoferhhi/vvenc#166]
```
In file included from CommonDef.h:63,
                 from Unit.h:48,
                 from Buffer.cpp:51:
In constructor 'vvenc::static_vector<T, N>::static_vector(std::initializer_list<_Tp>) [with T = vvenc::AreaBuf<short int>; long long unsigned int N = 3]',
    inlined from 'vvenc::UnitBuf<T>::UnitBuf(ChromaFormat, vvenc::AreaBuf<T>&&, vvenc::AreaBuf<T>&&, vvenc::AreaBuf<T>&&) [with T = short int]' at Buffer.h:675:157,
    inlined from 'vvenc::PelUnitBuf vvenc::PelStorage::getBuf(const vvenc::UnitArea&)' at Buffer.cpp:1054:179:
TypeDef.h:719:28: warning: writing 20 bytes into a region of size 4 [-Wstringop-overflow=]
  719 |     while( _src1 < _src2 ) _arr[ _size++ ] = *_src1++;
      |                            ^~~~
In file included from Unit.h:49:
Common.h: In member function 'vvenc::PelUnitBuf vvenc::PelStorage::getBuf(const vvenc::UnitArea&)':
Common.h:78:12: note: destination object 'vvenc::Size::width' of size 4
   78 |   SizeType width;
      |            ^~~~~
```

**Comment by adamjw24** [comment]
So is this on 64 or 32 bits build? We actually never test VVenC on 32 bits. It is very memory hungry, so you'd need to limit threads or resolution. But theoretically there is not reason for it not to work... The `static_vector` issue will be getting another fix soon tho, so maybe it'll resolve itself.

**Comment by adamjw24** [comment]
Would be great if you could have a look after #167. At some point we will include 32-bit build into the CI too

**Comment by Jamaika1** [comment]
Initial testing of gcc 13.0.0-29052022 win32
```
InterSearch.cpp:1727:46: warning: writing 24 bytes into a region of size 4 [-Wstringop-overflow=]
 1727 |               cu.mvd[REF_PIC_LIST_0][verIdx] = bestMvd[0][verIdx];
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from c:\msys1300\x86_64-w64-mingw32\include\commonlib\MotionInfo.h:50,
                 from c:\msys1300\x86_64-w64-mingw32\include\commonlib\Slice.h:52,
                 from c:\msys1300\x86_64-w64-mingw32\include\commonlib\Contexts.h:49,
                 from c:\msys1300\x86_64-w64-mingw32\include\commonlib\contextmodelling.h:49,
                 from CABACWriter.h:49,
                 from InterSearch.h:48,
                 from InterSearch.cpp:48:
c:\msys1300\x86_64-w64-mingw32\include\commonlib\Mv.h:82:9: note: destination object 'vvenc::Mv::hor' of size 4
   82 |   int   hor;     ///< horizontal component of motion vector
      |         ^~~
```

**Comment by adamjw24** [comment]
> Initial testing of gcc 13.0.0-29052022 win32
> 
> ```
> InterSearch.cpp:1727:46: warning: writing 24 bytes into a region of size 4 [-Wstringop-overflow=]
>  1727 |               cu.mvd[REF_PIC_LIST_0][verIdx] = bestMvd[0][verIdx];
>       |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
> In file included from c:\msys1300\x86_64-w64-mingw32\include\commonlib\MotionInfo.h:50,
>                  from c:\msys1300\x86_64-w64-mingw32\include\commonlib\Slice.h:52,
>                  from c:\msys1300\x86_64-w64-mingw32\include\commonlib\Contexts.h:49,
>                  from c:\msys1300\x86_64-w64-mingw32\include\commonlib\contextmodelling.h:49,
>                  from CABACWriter.h:49,
>                  from InterSearch.h:48,
>                  from InterSearch.cpp:48:
> c:\msys1300\x86_64-w64-mingw32\include\commonlib\Mv.h:82:9: note: destination object 'vvenc::Mv::hor' of size 4
>    82 |   int   hor;     ///< horizontal component of motion vector
>       |         ^~~
> ```

This is a bug for the GCC bugtracker. Our code seems fine there.

Is the original issue resolved? Can this be closed?
