### ISSUE TITLE
Question about LDB configuration

### ISSUE THREAD

**Issue by KingTuring** [fraunhoferhhi/vvenc#176]
Hi!

I think literal meaning of LDB is that it does not need to cache future images, so as to achieve low latency. But in the actual code implementation of vvenc, regardless of the configuration, a GOP-size frames will be cached first (regardless of MCTF is used) before encoding. In this case, what is the actual meaning of LDB?

Thanks in advance,
Jin.

**Comment by adamjw24** [comment]
Hi!

The actual meaning of LDB concerns the decoder, not the encoder. Basically, when you encode with that config, it means that the decoding order is the same as the output order. It does not put any constraints on the encoding.

VVenC is an offline-encoder, i.e. it cannot do live encoding. Given that constraint, encoder-sided Low-Delay is not viable with VVenC, not matter the buffer size. We concentrate the development on the main use-case of max-coding-gain encoding, using picture reordering. For this reason specific optimizations to buffer management for experimental use cases like low delay sometimes fall behind.

Hope this helps.

Best regards,
Adam

**Comment by KingTuring** [comment]
Hi!

Thanks for your quick reply. But I still have some questions about your reply:

>The actual meaning of LDB concerns the decoder, not the encoder.

In video conferencing, live broadcast, television broadcasting and other application scenarios, low delay at the encoder is very important.  So I'm curious if low latency should also target encoders?

>We concentrate the development on the main use-case of max-coding-gain encoding, using picture reordering. For this reason specific optimizations to buffer management for experimental use cases like low delay sometimes fall behind.

I think frames reordering is not necessary in the case of low latency. What do you think?

Thanks in advance,
Jin.

**Comment by adamjw24** [comment]
> In video conferencing, live broadcast, television broadcasting and other application scenarios, low delay at the encoder is very important. So I'm curious if low latency should also target encoders?

Of course it should. But as you mentioned, this is mostly interesting for _live_ applications, for which VVenC is not suited at this time.

> I think frames reordering is not necessary in the case of low latency. What do you think?

That is exactly what I am saying. It is not only not suited, it creates decoding delay, thus it is forbidden.

The low delay configs for VVenC are more of academical value at this point, that is why they are experimental.

**Comment by adamjw24** [comment]
We will rename the option to sth like "PictureReodering" to make it less confusing.
