### ISSUE TITLE
Will support 'ALFTempPred' for parallel processing?

### ISSUE THREAD

**Issue by Roudgers** [fraunhoferhhi/vvenc#186]
ALFTempPred is off by default now, but forcing it to open will cause the bug of bitstream inconsistency. Can 'ALFTempPred' support for parallel processing?

**Comment by adamjw24** [comment]
Short answer: Not really, no.

Long answer: not when processing multiple frames in parallel. You could set `MaxParallelFrames=1` and than it should work, but it would harm the parallel performance a lot.

**Comment by Roudgers** [comment]
I see. Thanks for your explanation and your hard work.

**Comment by adamjw24** [comment]
Sure thing.

Actually, I was corrected by my colleagues. The `ALFTempPred` functionality is not possible as it is, i.e. predicting from the same temporal layer (TL), but we might one day rewrite it to cross-TL prediction, which would be possible even with frame parallelism. So stay tuned, maybe we can get some of the (very minor) parallelisation losses back.

**Comment by Roudgers** [comment]
I firmly believe you will complete about it. Thanks again.
