### ISSUE TITLE
Quantization parameter with 2 passes

### ISSUE THREAD

**Issue by TyraVex** [fraunhoferhhi/vvenc#200]
Hello,

Would it be possible to achieve a variable bitrate compression set with --qp when using two passes?

Thanks

**Comment by adamjw24** [comment]
Hi,

what behavior would you exactly expect from a fix-QP run with two passes? If the QP is fix, why run the first pass?

For VVenC, the two-pass RC is produces a somehow variable bitrate, since the bits are spent where the content requires is, and saved where the content allows.

Best regards,
Adam

**Comment by TyraVex** [comment]
Hello,
Thank you for your reply.

Encoding a still and a shaky video with two passes will result in two videos having the same size. As a result, the shaky video will be worse in terms of quality compared to the still one.

I may be wrong and I am not an expert in video compression, but from my experience, allowing a quantization parameter while encoding with two passes would result with true variable bitrate videos (fixing the issue I mentionned above), while keeping the advantages of the two passes, which I believe helps the second pass taking better decisions, resulting with a more efficient output.

Regards
TyraVex

**Comment by adamjw24** [comment]
Why dont you just encode with QP and without rate control? This would have the exact effect you are describing. Just dont set any of the passes/NumPasses/pass/Pass/bitrate/TargetBitrate parameters, and just set the QP/qp parameter.

**Comment by adamjw24** [comment]
Closing for now, as this not a usecase that is supported with VVenC, nor is a plan to support it.
