### ISSUE TITLE
Showing the input parameters

### ISSUE THREAD

**Issue by birdie-github** [fraunhoferhhi/vvenc#206]
It would be really helpful if `vvenc` by _default_ (maybe there are options I've overlooked but still) showed the source video parameters, e.g.:

`1920x1080@30 yuv420`.

It currently doesn't and it's very easy to pipe something to it without specifying --size --rate and get total garbage as the output.

**Comment by jbrdbg** [comment]
Both expert and easy app could be configured to be more verbose. Simply use --Verbosity 6. This will give you, among other additional information, also the configured input size. Rate control configuration is shown in the encoder output by default. Look at the "RATE CONTROL CFG:" line in the output.

Besides, a short explanation on the Verbosity parameter can be found with the --fullhelp option.
