### ISSUE TITLE
Add VFR and VBV bitrate support (feature request)

### ISSUE THREAD

**Issue by MartinEesmaa** [fraunhoferhhi/vvenc#210]
Hello!

I would like feature request for variable frame rate and video buffering verifier into vvenc.
For example about variable frame rate, the computer screen record constant frame rate is 60fps, then I remove duplicate/unused frames using FFmpeg mpdecimate with H.264 encoder and saves compression artifacts & decreases file sizes. 

What about VVC VFR support?
I tried to encode from my H.264 video to VVC video using FFmpeg mpdecimate pipe with vvencapp:
```
ffmpeg -i example.mp4 -pix_fmt yuv420p -vf mpdecimate=hi=200:lo=200:frac=1:max=0 -f yuv4mpegpipe - | vvencapp --y4m -i - --preset slow --qp 32 -o example_variable.266
```
But it encoded VVC video codec only with constant frame rate after FFmpeg mpdecimate pipe with vvenc. Same with vvencffapp.

Also, I need VBV (Video Buffering Verifier) support too in vvenc, which allows streaming bitrates without loss of quality.

- Martin Eesmaa

**Comment by adamjw24** [comment]
Hi.

VVenC does not support variable frame-rate for now. It might be enabled oneday if it is integrated into some frameworks. As for now, VVenC cannot even deduce the timing information. It would need to be provided externally, and its most straightforward in a framework. The picture timing might be even be overwritten by some entity wrapping VVenC someday. I don't think this is really an issue for the core encoder.

Abour VBV, or HRD as it is called for VVC, we don't have support for it now. This might come sooner or later, but as far as I understand it is not mission critical, as long as VVenC is not used for live-streaming over limited bandwidth (i.e. satellite or terrestrial). For OTT it might be helpful, but its acceptable to be ignored.

Best regards,
Adam

**Comment by adamjw24** [comment]
> What about VVC VFR support? I tried to encode from my H.264 video to VVC video using FFmpeg mpdecimate pipe with vvencapp:
> 
> ```
> ffmpeg -i example.mp4 -pix_fmt yuv420p -vf mpdecimate=hi=200:lo=200:frac=1:max=0 -f yuv4mpegpipe - | vvencapp --y4m -i - --preset slow --qp 32 -o example_variable.266
> ```

If you look at your cmd, when you demux the mp4 into y4m, you loose the timing information. So VVenC is literally not provided the VFR info you want to retain.

**Comment by MartinEesmaa** [comment]
Okay, thank you for giving me more info. The two features might not be important to me, but optional necessary if needed. Feel free to close the issue for your choice. :)
