### ISSUE TITLE
How to set Main profile (not Main 10)

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#213]
I'm using VVC in 8-bit depth mode (for still pictures). The correct would be to use the Main profile, right? I have not find a way to set it, as I can see just Main10-based profile options. Am I missing something?

**Comment by adamjw24** [comment]
VVC doesn't have an 8-bit only profile, like "Main Still Picture" from HEVC. You should stick to "Main 10 Still Picture" for your use case.

**Comment by rafael2k** [comment]
Perfect. Thanks Adam. Sorry to bother!
