### ISSUE TITLE
support: can I pay someone to ssh into my Debian based system to compile for me

### ISSUE THREAD

**Issue by weiwu-zhang** [fraunhoferhhi/vvenc#218]
I wish to have a version of ffmpeg that can compress to h.266 but I do not want to struggle with compile dependencies and all sorts of things. Can I ask a team member to do this by ssh into my host? I'll close this issue as soon as I get someone or after a few days.

Kindly forgive that I'm just time-poor not unwilling to learn.

**Comment by MartinEesmaa** [comment]
Hello, @weiwu-zhang.

You can use my prebuilt FFmpeg VVC custom static build, but only FFplay does not work:
https://github.com/MartinEesmaa/VVCEasy/blob/master/FFMPEGVVC.md#ffmpeg-downloads-xhe-aac--vvc-endecoder-plugin-compiled-by-martin-eesmaa

It's the best way not to pay someone to ssh into your Debian system, but it's my optional choice.

Let me know if you have any issues or questions to me. :)

Regards
- Martin Eesmaa
