### ISSUE TITLE
Support ISO BMFF output for still picture encode

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#22]
Hi,
Is there planned support for ISOMBFF output support - especially for still image coding?

**Comment by rafael2k** [comment]
May be adding support to libheif support is the way to go?
https://github.com/strukturag/libheif

**Comment by rafael2k** [comment]
Do you at Fraunhofer could provide some sample still images stored in ISO base media file format?

**Comment by adamjw24** [comment]
I think ISOMBFF support for VVC is not yet standarized fully, but in a last pre-final stage of the process (probably no more changes). It would be nice to have this once its ready. Incorporation into an external packager like libheif sounds like the way to go.

I'll leave the help wanted tag on this issue, since it'd be nice to have some support there.

**Comment by rafael2k** [comment]
Hi Adam, thanks. I talked to Dirk, of libheif, and he thinks it will be straightforward to support FhG VVC implementation (do you have any suggestion in this regards?). I downloaded the amendments which are in the ISO voting system, and as it is really unlikely that there will be any change, I think we can already start the work. In case you know any place where we could have a ISO MBFF VVC sample, let us know.

**Comment by adamjw24** [comment]
I actually think that GPAC (current HEAD) already can mux elementary bitstreams as produced by VVenC to an .mp4 file. Maybe give it a try. Let us know if there are any issues with VVenC or the interface.
Thanks, Adam

**Comment by rafael2k** [comment]
I'll take a look in GPAC - thanks Adam.

**Comment by adamjw24** [comment]
VVenC will always be a core encoder producing AnnexB raw bitstream, and leaving the muxing to frameworks like FFmpeg or GPAC. The latter already has initial implementation.

Closing.
