### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [fraunhoferhhi/vvenc#246]
I would like to point out that an identifier like “[`_VVENC_H_`](https://github.com/fraunhoferhhi/vvenc/blob/6df066883cf52a4a0faf7be5eb6f0e572afedf34/include/vvenc/vvenc.h#L47 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elfring** [comment]
:thought_balloon: How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by adamjw24** [comment]
> 💭 How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106)?

Please keep to the discussion in the topic. If you find undefined behavior constructs please let us know pointing to our code. This is borderline spam.

**Comment by elfring** [comment]
>If you find undefined behavior constructs please let us know pointing to our code.

:eyes: I did that for two questionable include guards already.

:thought_balloon: Would you like to [take another look at linked information sources](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Documentation")?
