### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fraunhoferhhi/vvenc#247]
Would you like to add more error handling for return values from functions like the following?
* [fopen](https://pubs.opengroup.org/onlinepubs/9699919799/functions/fopen.html "Open a stream") ⇒ [printSummary](https://github.com/fraunhoferhhi/vvenc/blob/6df066883cf52a4a0faf7be5eb6f0e572afedf34/source/Lib/EncoderLib/Analyze.h#L411)
* [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [vvenc_accessUnit_alloc](https://github.com/fraunhoferhhi/vvenc/blob/6df066883cf52a4a0faf7be5eb6f0e572afedf34/source/Lib/vvenc/vvenc.cpp#L113)

**Comment by elfring** [comment]
* :thinking: How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?
* :crystal_ball: How will chances evolve to benefit any more also from [the means of aspect-oriented software development](https://en.wikipedia.org/wiki/Aspect-oriented_programming "Documentation")?

**Comment by adamjw24** [comment]
Please don't diverge from the topic of the issue. This is not a forum.

**Comment by elfring** [comment]
:crystal_ball: Which development techniques would you prefer for the completion of error detection and corresponding exception handling?

**Comment by elfring** [comment]
:eyes: Further update candidates were left over.

Example:
https://github.com/fraunhoferhhi/vvenc/blob/2cdefe367969e6e33ede630cca365ad06ac7c476/source/Lib/EncoderLib/Analyze.h#L411-L466

:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
