### ISSUE TITLE
Built Windows binary using mingw-gcc for faster encoding time

### ISSUE THREAD

**Issue by meongmeongasd** [fraunhoferhhi/vvenc#25]
## vvencapp.exe compiled using gcc+mingw have 7-9x faster encoding time than binaries compiled using msvc

![graph](https://user-images.githubusercontent.com/80136789/110192711-5e5d4e00-7e62-11eb-8a48-9238a9c966bd.png)

### System Information

OS Platform and Distribution: Windows 10 Home Insider Preview build 21327.rs_prerelease.210226-1427, Windows 10 Education N 20H2 build 19042.631 (virtual machine)
Vvenc version 				: 0.3
Processor 					: i3-6100
RAM 						: 8gb
GCC							: 10.2
Mingw64						: latest
Visual Studio				: 16.9.0

## What about the video source ?
4 different video(test1, test2, test3, test4) 
-1080p source
-23.976 fps 
-5 second duration
cant share because copyright

## What about the output?
There is no difference between output from 2 binaries, checked with hash too.
![hash](https://user-images.githubusercontent.com/80136789/110191824-17b92500-7e5d-11eb-8611-7d027989a608.png)

## What about the binaries?
![binaries size](https://user-images.githubusercontent.com/80136789/110192792-eb080c00-7e62-11eb-9646-3dbe92d810b2.png)

## for msvc binary
1. Install visual studio 2019 with Desktop Development with C++
2. Download vvenc 0.30 release then extract
3. Open extracted folder with visual studio
4. Build all

## for gcc-mingw binary (tested in fresh install windows 10)
1. Install visual studio 2019 with Desktop Development with C++, MSYS2 here https://www.msys2.org/, CMAKE GUI here https://cmake.org/download/ (add CMAKE to path)
2. open mingw64.exe in MSYS2 installation directory then run these command
```
pacman -S base-devel gcc vim cmake
pacman -S mingw-w64-x86_64-toolchain
pacman -S mingw-w64-x86_64-cmake
pacman -S git
git clone https://github.com/fraunhoferhhi/vvenc.git
```
3. add D:\MSYS2\mingw64\bin to path (this an example, use your installation directory)
4. open CMAKE GUI follow these steps
![cmake step 1](https://user-images.githubusercontent.com/80136789/110193404-3ff95180-7e66-11eb-81e2-5f97b4468d5e.png)
![cmake step 2](https://user-images.githubusercontent.com/80136789/110193405-412a7e80-7e66-11eb-963f-37d123b2934e.png)
![cmake step 3](https://user-images.githubusercontent.com/80136789/110193406-42f44200-7e66-11eb-8945-769a6ead0023.png)
![cmake step 4](https://user-images.githubusercontent.com/80136789/110193409-44256f00-7e66-11eb-8547-8c88f77bff6a.png)

5. open mingw64.exe again then run these command
```
cd vvenc
cd build
make
cd ..
make
wait until compiling done
binary in ~/vvenc/bin/release-static
 ```
## Whats the command used?

vvencapp_msvc --preset faster -c yuv420 -i test1.yuv -s 1920x1080 -o test1_msvc_2019.266
vvencapp_msvc --preset faster -c yuv420 -i test2.yuv -s 1920x1080 -o test2_msvc_2019.266
vvencapp_msvc --preset faster -c yuv420 -i test3.yuv -s 1920x1080 -o test3_msvc_2019.266
vvencapp_msvc --preset faster -c yuv420 -i test4.yuv -s 1920x1080 -o test4_msvc_2019.266

vvencapp_mingw_gcc --preset faster -c yuv420 -i test1.yuv -s 1920x1080 -o test1_mingw64_gcc_10_2.266
vvencapp_mingw_gcc --preset faster -c yuv420 -i test2.yuv -s 1920x1080 -o test2_mingw64_gcc_10_2.266
vvencapp_mingw_gcc --preset faster -c yuv420 -i test3.yuv -s 1920x1080 -o test3_mingw64_gcc_10_2.266
vvencapp_mingw_gcc --preset faster -c yuv420 -i test4.yuv -s 1920x1080 -o test4_mingw64_gcc_10_2.266

## How do you test it?

1. Restart windows 
2. Run 4 command in succession for gcc-mingw binary 
3. Restart windows 
4. Run 4 command in succession for msvc binary

### Remarks
Hopefully in the future there is official way to create windows binary using gcc-mingw and added to documentation because the different in encoding times.
Please feel free to relay your comments, suggestions, questions.
Sorry for my bad english.

CMD output
[mingw_gcc.txt](https://github.com/meongmeongasd/ndfg/files/6094556/mingw_gcc.txt)
[msvc_2019.txt](https://github.com/meongmeongasd/ndfg/files/6094557/msvc_2019.txt)

**Comment by davFaithid** [comment]
Both CMD output files lead to an error page saying "Not Found".

**Comment by meongmeongasd** [comment]
> Both CMD output files lead to an error page saying "Not Found".

here fixed
[mingw_gcc.txt](https://github.com/fraunhoferhhi/vvenc/files/6095684/mingw_gcc.txt)
[msvc_2019.txt](https://github.com/fraunhoferhhi/vvenc/files/6095685/msvc_2019.txt)

**Comment by meongmeongasd** [comment]
Video source 		: https://media.xiph.org/video/derf/ Ctrl+f mobcal and then cut it to the 1st 3 second

command
```
ffmpeg -i 720p50_mobcal_ter.y4m -t 3 -c:v rawvideo -pix_fmt yuv420p 720p50_mobcal_ter_3sec.yuv
vvencapp_mingw_gcc --preset faster -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_mingw_gcc_faster.h266
vvencapp_mingw_gcc --preset fast -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_mingw_gcc_fast.h266
vvencapp_mingw_gcc --preset medium -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_mingw_gcc_medium.h266
vvencapp_mingw_gcc --preset slow -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_mingw_gcc_slow.h266
vvencapp_mingw_gcc --preset slower -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_mingw_gcc_slower.h266
reboot
vvencapp_msvc --preset faster -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_msvc_faster.h266
vvencapp_msvc --preset fast -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_msvc_fast.h266
vvencapp_msvc --preset medium -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_msvc_medium.h266
vvencapp_msvc --preset slow -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_msvc_slow.h266
vvencapp_msvc --preset slower -c yuv420 -i 720p50_mobcal_ter_3sec.yuv -s 1280x720 -o 720p50_mobcal_ter_3sec_msvc_slower.h266
```
![yet another graph](https://user-images.githubusercontent.com/80136789/110224511-edc03b00-7f0e-11eb-80c8-a71afff4d294.png)

**Comment by f11894** [comment]
Aren't both binaries built with MSVC?
The notation "VS 1928" is in both CMD outputs.

**Comment by adamjw24** [comment]
Judging by the binary size, your MSVC binary is a Debug build. This would explain the runtime differences.

Also, about your build. If you are building the app to run, not to develop, you can uncheck the following build options:
* VVENC_ENABLE_TRACING
* VVENC_USE_ADDRESS_SANITIZER
* VVCEncoderLib_ENABLE_ITT

**Comment by meongmeongasd** [comment]
@adamjw2 Thanks for the feed back, sorry for the incovenience. That mistake not realizing debug build and release build is my part. I will close the issue.
