### ISSUE TITLE
media-autobuild_suite-master - libvvenc and libvvdec -Patch could not be applied with `git am`

### ISSUE THREAD

**Issue by F1EJP** [fraunhoferhhi/vvenc#250]
Hi
After compiling with your instructions no encoder or decoder VVC
Maybe i made a mistake ?
see log
[media-autobuild_suite.ini.txt](https://github.com/fraunhoferhhi/vvenc/files/10936586/media-autobuild_suite.ini.txt)
[compile.log](https://github.com/fraunhoferhhi/vvenc/files/10936597/compile.log)
Thanks for all

Dominique

**Comment by adamjw24** [comment]
We update our wiki to show how to specify a FFmpeg version, see https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#windows (point 3). Hope this resolves it.

Best, Adam

**Comment by F1EJP** [comment]
Thank you so much !
I look that
