### ISSUE TITLE
Decode h266 bit stream but output yuv size is not same to raw yuv size

### ISSUE THREAD

**Issue by UpTownCat** [fraunhoferhhi/vvenc#27]
I use vvencapp encode a 3s yuv file then use DecoderAppStatic provided by VTM to decode bit stream, but decoding output yuv file size is 2x compare to raw yuv size. Do I use the wrong decoder?

`./vvencapp  -i seg_1.yuv -s 640x360 -b 350000 -r 24 --preset fast -o tmp.h266`
`./DecoderAppStatic -b tmp.h266 -o tmp.yuv`
`-rw-rw-r-- 1 ec2-user ec2-user 24883200 Mar 12 05:00 seg_1.yuv`
`-rw-rw-r-- 1 ec2-user ec2-user 49766400 Mar 12 08:09 tmp.yuv`

**Comment by eimran-eimon** [comment]
Please check this closed issue: [Output yuv file size increased](https://github.com/fraunhoferhhi/vvenc/issues/26)

**Comment by UpTownCat** [comment]
Thanks
