### ISSUE TITLE
[Feature Request] PSNR

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#270]
Hi, how can i disable PSNR calculation this will slow down encoding process a bit, is there any command line options or u can add this feature, so the user can disable PSNR calculation frame by frame, it will increase encoding speed a bit

thanks

**Comment by adamjw24** [comment]
This is not possible as of now.

I am not convinced it has a lot of impact, but I'll check that. I think VVenC is still too slow for such a minor additional calculation to have an impact.

**Comment by adamjw24** [comment]
We ran the test, and for faster with 8 threads the encoder gets like 0.5% faster when not calculating PSNR. This is not worth the effort of removing it. If we manage to have a preset that is like 5x faster at some point, the effect should increase to 2-3%, we might reconsider at that time.
