### ISSUE TITLE
Add y4m option to help text

### ISSUE THREAD

**Issue by jungleboynx** [fraunhoferhhi/vvenc#271]
The y4m switch already exists for stdin piping but isn't mentioned in the help text. I had to search to code to find the switch.

Example of 10bit stack16 piping into VVC:
set P1=-q %1 --preset fast -c yuv420_10 -t 12 --sdr sdr_709
avs2yuv -depth 10 ..\video1.avs - | vvencapp %P1% --y4m -i - -o ..\video1.vvc

**Comment by lehmann-c** [comment]
It´s already in the help. 
use --fullhelp, to see all available options:
vvencapp --fullhelp
...
        --y4m [0]                    force y4m input (only needed for input pipe, else enabled by .y4m file extension)
...
