### ISSUE TITLE
Add encoder settings to VVC file

### ISSUE THREAD

**Issue by jungleboynx** [fraunhoferhhi/vvenc#272]
A useful addition would be more encoder information similar to x264 and x265 when viewed with MediaInfo.

Like this:

Format profile                           : Main|Main10|Main12@L4|5|6
Color space                              : YUV|RGB
Chroma subsampling                       : 4:2:0|4:2:2|4:4:4
Bit depth                                : 8|10|12 bits
Pixel Format                             : yuv420p10|yuv420p12
Writing library                          : VVC encoder version
Encoding settings                        : cpuid=1111039 ...etc
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

I just makes it easier to see what encoder options were used.

**Comment by lehmann-c** [comment]
These kind of information are already available for every bitstream that is encoded with VVenC.
When MediaInfo isn´t showing the correct information it has to be implemented in the MediaInfo application.
