### ISSUE TITLE
Film grain synthesis?

### ISSUE THREAD

**Issue by Equadex** [fraunhoferhhi/vvenc#278]
Film grain synthesis is neccessary for good compression of noisy images but it doesn't seem to be exposed in the encoder. I would like to suggest for this to be implemented as a feature enhancement.

**Comment by adamjw24** [comment]
Correct me if I'm wrong, but film grain for VVC has not yet been finalized? We are indeed waiting for the finalization of the spec on this and would very much like to have it.

So stay tuned

**Comment by adamjw24** [comment]
My bad. FG for VVC is actually ready to go. I guess we'll put on the roadmap soon.

**Comment by adamjw24** [comment]
Experimental support added in #394 . VVdeC now also support decoding of VSEI FGS SEI, so you can check the results easily as well.
