### ISSUE TITLE
8 bit encoding 

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#281]
Hi, i tried to use yuv420p file and set internal bitdepth to 8 but profile it assigns always 10 bit (main10)

./vvencFFapp -i D:\00000_out.raw -s 1920x1080 --fps 24000/1001 -b teste.266 --OutputBitDepth 8 -t 28 --Tiles 5x5 --NumPasses 1 --LookAhead 1 --TargetBitrate 1.5M --Verbosity info --preset faster --InternalBitDepth 8 --OutputBitDepth 8 --ColourPrimaries bt709 --TransferCharacteristics bt709 --MatrixCoefficients bt709 --ColourDescriptionPresent 1 --Hdr off --WavefrontSynchro 1
Its a bug or can't encode 8bit files?
It encode 8 bit but profile always main10

**Comment by thx4ever** [comment]
OK thanks. About the latest branch master, u added statistics information but it shows in many lines down so its possible to only update the current status not add a new line ...?
For example
The command show alot of lines 
vvenc [info]: stats:   6.5% frame=  4248/65460 fps= 13.1 avg_fps=  7.9 bitrate= 1934.76 kbps avg_bitrate= 1493.43 kbps elapsed= 00h:09m:00s left= 02h:09m:38s
vvenc [info]: stats:   6.5% frame=  4272/65460 fps=  7.3 avg_fps=  7.9 bitrate= 1688.83 kbps avg_bitrate= 1494.53 kbps elapsed= 00h:09m:04s left= 02h:09m:38s
vvenc [info]: stats:   6.6% frame=  4296/65460 fps=  8.2 avg_fps=  7.9 bitrate= 1618.71 kbps avg_bitrate= 1495.22 kbps elapsed= 00h:09m:06s left= 02h:09m:34s
vvenc [info]: stats:   6.6% frame=  4320/65460 fps=  7.3 avg_fps=  7.9 bitrate=  650.89 kbps avg_bitrate= 1490.53 kbps elapsed= 00h:09m:10s left= 02h:09m:34s
vvenc [info]: stats:   6.6% frame=  4344/65460 fps= 12.8 avg_fps=  7.9 bitrate= 1815.86 kbps avg_bitrate= 1492.33 kbps elapsed= 00h:09m:12s left= 02h:09m:14s
vvenc [info]: stats:   6.7% frame=  4368/65460 fps=  6.1 avg_fps=  7.9 bitrate= 2789.30 kbps avg_bitrate= 1499.45 kbps elapsed= 00h:09m:16s left= 02h:09m:23s
vvenc [info]: stats:   6.7% frame=  4392/65460 fps=  6.7 avg_fps=  7.9 bitrate= 2804.35 kbps avg_bitrate= 1506.58 kbps elapsed= 00h:09m:19s left= 02h:09m:28s
vvenc [info]: stats:   6.7% frame=  4416/65460 fps=  6.9 avg_fps=  7.9 bitrate=  868.60 kbps avg_bitrate= 1503.12 kbps elapsed= 00h:09m:23s left= 02h:09m:31s
vvenc [info]: stats:   6.8% frame=  4440/65460 fps= 15.0 avg_fps=  7.9 bitrate= 1799.06 kbps avg_bitrate= 1504.71 kbps elapsed= 00h:09m:24s left= 02h:09m:07s
vvenc [info]: stats:   6.8% frame=  4464/65460 fps=  7.3 avg_fps=  7.9 bitrate= 1427.23 kbps avg_bitrate= 1504.30 kbps elapsed= 00h:09m:27s left= 02h:09m:07s
vvenc [info]: stats:   6.9% frame=  4488/65460 fps=  7.4 avg_fps=  7.9 bitrate= 1839.10 kbps avg_bitrate= 1506.09 kbps elapsed= 00h:09m:31s left= 02h:09m:07s
vvenc [info]: stats:   6.9% frame=  4512/65460 fps=  7.4 avg_fps=  7.9 bitrate=  833.85 kbps avg_bitrate= 1502.51 kbps elapsed= 00h:09m:34s left= 02h:09m:06s
vvenc [info]: stats:   6.9% frame=  4536/65460 fps= 15.1 avg_fps=  7.9 bitrate= 1629.08 kbps avg_bitrate= 1503.18 kbps elapsed= 00h:09m:36s left= 02h:08m:44s
vvenc [info]: stats:   7.0% frame=  4560/65460 fps=  7.2 avg_fps=  7.9 bitrate= 1561.09 kbps avg_bitrate= 1503.49 kbps elapsed= 00h:09m:39s left= 02h:08m:44s
vvenc [info]: stats:   7.0% frame=  4584/65460 fps=  7.1 avg_fps=  7.9 bitrate= 1733.17 kbps avg_bitrate= 1504.69 kbps e

So can be possible to it update only the line not add a new line every encoded frame?
It shoul only one line vvenc [info]: stats:   7.0% frame=  4560/65460 fps=  7.2 avg_fps=  7.9 bitrate= 1561.09 kbps avg_bitrate= 1503.49 kbps elapsed= 00h:09m:39s left= 02h:08m:44s and when next number of encode only update the current line?

Sorry for my bad english

**Comment by adamjw24** [comment]
> OK thanks. About the latest branch master, u added statistics information but it shows in many lines down so its possible to only update the current status not add a new line ...? For example The command show alot of lines
> 
> vvenc [info]: stats: 6.5% frame= 4248/65460 fps= 13.1 avg_fps= 7.9 bitrate= 1934.76 kbps avg_bitrate= 1493.43 kbps elapsed= 00h:09m:00s left= 02h:09m:38s
> vvenc [info]: stats: 6.5% frame= 4272/65460 fps= 7.3 avg_fps= 7.9 bitrate= 1688.83 kbps avg_bitrate= 1494.53 kbps elapsed= 00h:09m:04s left= 02h:09m:38s
> ...
vvenc [info]: stats: 7.0% frame= 4560/65460 fps= 7.2 avg_fps= 7.9 bitrate= 1561.09 kbps avg_bitrate= 1503.49 kbps elapsed= 00h:09m:39s left= 02h:08m:44s
> vvenc [info]: stats: 7.0% frame= 4584/65460 fps= 7.1 avg_fps= 7.9 bitrate= 1733.17 kbps avg_bitrate= 1504.69 kbps e
> 
> So can be possible to it update only the line not add a new line every encoded frame? It shoul only one line vvenc [info]: stats: 7.0% frame= 4560/65460 fps= 7.2 avg_fps= 7.9 bitrate= 1561.09 kbps avg_bitrate= 1503.49 kbps elapsed= 00h:09m:39s left= 02h:08m:44s and when next number of encode only update the current line?
> 

We will not adapt that. Please use `sed` or similar lightweight wrapper to achieve that.

> Sorry for my bad english So we make a gui for this program, u dont need to read every line but only the current line updated
> 
> when i set --InternalBitDepth [8] this error happens
> 
> Parameter Check Error: InternalBitDepth must be at least 10 bit for HDR but im not encoding HDR my current options ./vvencFFapp -i D:\00000_out.raw -s 1920x1080 --fps 24000/1001 -b teste.266 -t 28 --NumPasses 1 --LookAhead 1 --TargetBitrate 1.5M --Verbosity info --preset fast --Sdr sdr_709 --Tiles 2x2 --OutputBitDepth 8 --InternalBitDepth 8 When i remove this option --Sdr sdr_709 it works The latest code looks good but have one problem with 2 pass encoding, when doing 2 pass --pass 1 with stats it does not show statistics so we need to use verbosity level verbose in the first pass analysis

This is a bug on our side. We'll fix it soon, just a bad parameter check.
