### ISSUE TITLE
Encoder low delay settings?

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#284]
Hi, i want to know how to use lowdelay settings for vvencapp and vvencFFapp

**Comment by adamjw24** [comment]
For vvencapp:
use ` --additional GopSize=8:PicReordering=0 -rt 0`

For vvencFFapp:
use `--GopSize=8 --PicReordering=0 --DecodingRefreshType=0`

**Comment by thx4ever** [comment]
Thanks
