### ISSUE TITLE
problem to encode VVC

### ISSUE THREAD

**Issue by harinitw** [fraunhoferhhi/vvenc#285]
sir I successfully encoded a video with the HM programme, but I ran into trouble with the VVC encoding, sir. I watched one YouTube video. His name is martin eesmaa. That built the folder and opened the ALL_BUILD solution file as instructed. I've included an error in the build solution where the RUN tests issue appeared when I built the solution. Sir, I addressed the errors below. And also how to add explain the process for including configuration files in command parameters. Sincere gratitude, sir

7/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/7: Test_vvenclibtest-timestamps ..................... Passed 60.92 sec
3> Start 8: Test_vvencapp-tooltest
3> 8/43 Test https://github.com/MartinEesmaa/VVCEasy/discussions/8: Test_vvencapp-tooltest ...........................***Exception: Illegal 5.66 sec
3> Start 9: Test_vvencFFapp-tooltest
3> 9/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/9: Test_vvencFFapp-tooltest .........................***Exception: Illegal 6.10 sec
3> Start 10: Test_compare_output-tooltest
3>Failed test dependencies: Test_vvencFFapp-tooltest Test_vvencapp-tooltest
3>10/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/10: Test_compare_output-tooltest .....................***Not Run 0.00 sec
3> Start 11: Test_vvencFFapp-tooltest-Scalar
3>11/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/11: Test_vvencFFapp-tooltest-Scalar .................. Passed 10.21 sec
3> Start 12: Test_compare_output-tooltest-Scalar
3>Failed test dependencies: Test_vvencapp-tooltest
3>12/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/12: Test_compare_output-tooltest-Scalar ..............***Not Run 0.00 sec
3> Start 13: Test_vvencFFapp-tooltesttrans
3>13/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/13: Test_vvencFFapp-tooltesttrans ....................***Exception: Illegal 0.49 sec
3> Start 14: Test_output-tooltesttrans
3>Failed test dependencies: Test_vvencFFapp-tooltesttrans
3>14/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/14: Test_output-tooltesttrans ........................***Not Run 0.00 sec
3> Start 15: Test_vvencapp-faster
3>15/43 Test https://github.com/MartinEesmaa/VVCEasy/pull/15: Test_vvencapp-faster ............................. Passed 0.70 sec
3> Start 16: Test_vvencFFapp-faster
3>16/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/16: Test_vvencFFapp-faster ........................... Passed 0.80 sec
3> Start 17: Test_compare_output-faster
3>17/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/17: Test_compare_output-faster ....................... Passed 0.03 sec
3> Start 18: Test_vvencapp-fast
3>18/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/18: Test_vvencapp-fast ............................... Passed 1.23 sec
3> Start 19: Test_vvencFFapp-fast
3>19/43 Test #19: Test_vvencFFapp-fast ............................. Passed 1.29 sec
3> Start 20: Test_compare_output-fast
3>20/43 Test https://github.com/MartinEesmaa/VVCEasy/discussions/20: Test_compare_output-fast ......................... Passed 0.02 sec
3> Start 21: Test_vvencFFapp-transcoding
3>21/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/21: Test_vvencFFapp-transcoding ...................... Passed 0.49 sec
3> Start 22: Test_output-transcoding
3>22/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/22: Test_output-transcoding .......................... Passed 0.02 sec
3> Start 23: Test_vvencapp-medium
3>23/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/23: Test_vvencapp-medium .............................***Exception: Illegal 2.32 sec
3> Start 24: Test_vvencFFapp-medium
3>24/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/24: Test_vvencFFapp-medium ...........................***Exception: Illegal 2.30 sec
3> Start 25: Test_compare_output-medium
3>Failed test dependencies: Test_vvencFFapp-medium Test_vvencapp-medium
3>25/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/25: Test_compare_output-medium .......................***Not Run 0.00 sec
3> Start 26: Test_vvencapp-slow
3>26/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/26: Test_vvencapp-slow ............................... Passed 5.78 sec
3> Start 27: Test_vvencFFapp-slow
3>27/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/27: Test_vvencFFapp-slow ............................. Passed 5.99 sec
3> Start 28: Test_compare_output-slow
3>28/43 Test https://github.com/MartinEesmaa/VVCEasy/issues/28: Test_compare_output-slow ......................... Passed 0.02 sec
3> Start 29: Test_vvencapp-medium_noqpa_0thr
3>29/43 Test #29: Test_vvencapp-medium_noqpa_0thr ..................***Exception: Illegal 1.64 sec
3> Start 30: Test_vvencFFapp-medium_noqpa_0thr
3>30/43 Test #30: Test_vvencFFapp-medium_noqpa_0thr ................***Exception: Illegal 1.73 sec
3> Start 31: Test_compare_output-medium_noqpa_0thr
3>Failed test dependencies: Test_vvencFFapp-medium_noqpa_0thr Test_vvencapp-medium_noqpa_0thr
3>31/43 Test #31: Test_compare_output-medium_noqpa_0thr ............***Not Run 0.00 sec
3> Start 32: Test_vvencFFapp-lowdelay_medium_enc
3>32/43 Test #32: Test_vvencFFapp-lowdelay_medium_enc ..............***Exception: Illegal 3.34 sec
3> Start 33: Test_vvencFFapp-lowdelay_medium_dec
3>Failed test dependencies: Test_vvencFFapp-lowdelay_medium_enc
3>33/43 Test #33: Test_vvencFFapp-lowdelay_medium_dec ..............***Not Run 0.00 sec
3> Start 34: Test_vvencapp-medium_rc2p
3>34/43 Test #34: Test_vvencapp-medium_rc2p ........................ Passed 3.33 sec
3> Start 35: Test_vvencFFapp-medium_rc2p
3>35/43 Test #35: Test_vvencFFapp-medium_rc2p ...................... Passed 2.87 sec
3> Start 36: Test_compare_output-medium_rc2p
3>36/43 Test #36: Test_compare_output-medium_rc2p .................. Passed 0.02 sec
3> Start 37: Test_vvencFFapp-medium_rc2p_statsFile1_exp
3>37/43 Test #37: Test_vvencFFapp-medium_rc2p_statsFile1_exp ....... Passed 0.47 sec
3> Start 38: Test_vvencFFapp-medium_rc2p_statsFile2_exp
3>38/43 Test #38: Test_vvencFFapp-medium_rc2p_statsFile2_exp ....... Passed 2.80 sec
3> Start 39: Test_compare_output-medium_rc2p_statsFile_exp
3>39/43 Test #39: Test_compare_output-medium_rc2p_statsFile_exp .... Passed 0.02 sec
3> Start 40: Test_vvencapp-medium_rc2p_statsFile1_easy
3>40/43 Test #40: Test_vvencapp-medium_rc2p_statsFile1_easy ........ Passed 0.47 sec
3> Start 41: Test_vvencapp-medium_rc2p_statsFile2_easy
3>41/43 Test #41: Test_vvencapp-medium_rc2p_statsFile2_easy ........ Passed 2.86 sec
3> Start 42: Test_compare_output-medium_rc2p_statsFile_easy
3>42/43 Test #42: Test_compare_output-medium_rc2p_statsFile_easy ... Passed 0.02 sec
3> Start 43: Cleanup_remove_temp_files
3>43/43 Test #43: Cleanup_remove_temp_files ........................ Passed 0.02 sec
3>
3>67% tests passed, 14 tests failed out of 43
3>
3>Total Test time (real) = 146.58 sec
3>
3>The following tests FAILED:
3> 8 - Test_vvencapp-tooltest (ILLEGAL)
3> 9 - Test_vvencFFapp-tooltest (ILLEGAL)
3> 10 - Test_compare_output-tooltest (Not Run)
3> 12 - Test_compare_output-tooltest-Scalar (Not Run)
3> 13 - Test_vvencFFapp-tooltesttrans (ILLEGAL)
3> 14 - Test_output-tooltesttrans (Not Run)
3> 23 - Test_vvencapp-medium (ILLEGAL)
3> 24 - Test_vvencFFapp-medium (ILLEGAL)
3> 25 - Test_compare_output-medium (Not Run)
3> 29 - Test_vvencapp-medium_noqpa_0thr (ILLEGAL)
3> 30 - Test_vvencFFapp-medium_noqpa_0thr (ILLEGAL)
3> 31 - Test_compare_output-medium_noqpa_0thr (Not Run)
3> 32 - Test_vvencFFapp-lowdelay_medium_enc (ILLEGAL)
3> 33 - Test_vvencFFapp-lowdelay_medium_dec (Not Run)

**Comment by adamjw24** [comment]
Please make an issue in the https://github.com/MartinEesmaa/VVCEasy repo. I don't know what custom build problems are causing your issues.
