### ISSUE TITLE
VVenC does not compile in C++17

### ISSUE THREAD

**Issue by bart-kroon** [fraunhoferhhi/vvenc#29]
Dear video expert,

We have included VVenC and VVdeC as sub-projects of the [TMIV 8](https://gitlab.com/mpeg-i-visual/tmiv) project.

An Apple user has reported problems building on AppleClang 12 because C++14 features are not enabled. I could fix that in a non-intrusive way by adding `target_compile_features(vvenc PUBLIC cxx_std_14)` and same for `vvdec`. (To be confirmed by that user.)

However, because TMIV itself is a C++17 project, I first tried `cxx_std_17`. This unfortunately does not work:

```
In file included from /home/videssa/bart/tmiv.486-c-14-flag-for-v8-0.clang.build/_deps/vvenc-src/source/Lib/CommonLib/PicYuvMD5.cpp:50:
/home/videssa/bart/tmiv.486-c-14-flag-for-v8-0.clang.build/_deps/vvenc-src/source/Lib/vvenc/../CommonLib/MD5.h:232:5: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
    register uint32_t a, b, c, d;
    ^~~~~~~~~
```

This was tested using v0.2.0.0, but [the same line](https://github.com/fraunhoferhhi/vvenc/blob/0f0f08f305f5d1f341c699b27791cae8b83e1d66/source/Lib/CommonLib/MD5.h#L232) is present on the main branch.

No hurry, but could you please make VVenC and VVdeC C++17 (or even C++20) compatible?

Best regards,

Bart

**Comment by podborski** [comment]
Deprecated `register` keyword was removed since C++17 https://en.cppreference.com/w/cpp/keyword/register

**Comment by adamjw24** [comment]
Will fix that in the next version soon. Since this is already as good as out the door, compatibility with C++20 might need to wait for the next version because of required additional testing.

**Comment by bart-kroon** [comment]
@adamjw24 , this issue may need to be reopened because there is another problem (again not urgent), this time in Mv.h, and VC16 refuses to build v0.3.1.0 in C++17 mode.

```
source\Lib\CommonLib\Mv.h(298,40): error C2039: 'unary_function': is not a member of 'std' 
source\Lib\CommonLib\Mv.h(295): message : see declaration of 'std' [C:\Data\TM1.vc16-release.build\_deps\vvenc-build\source\Lib\vvenc\vvenc.vcxproj]
source\Lib\CommonLib\Mv.h(298,1): error C2504: 'unary_function': base class undefined 
source\Lib\CommonLib\Mv.h(298,54): error C2143: syntax error: missing ',' before '<' 
```

`std::unary_function` is deprecated in C++11 and removed in C++17: https://en.cppreference.com/w/cpp/utility/functional/unary_function

Commenting out the base class appears to work. With below change I am able to build VVenC v0.3.1.0 as a C++17 sub-project.

```c++
namespace std
{
  template <>
  struct hash<vvenc::Mv> //: public std::unary_function<vvenc::Mv, uint64_t>
  {
    uint64_t operator()(const vvenc::Mv& value) const
    {
      return (((uint64_t)value.hor << 32) + value.ver);
    }
  };
}
```
