### ISSUE TITLE
Encoder crash when using single-thread.

### ISSUE THREAD

**Issue by zhijie1996** [fraunhoferhhi/vvenc#290]
I used the following parameter to encode a video. It will crash when RC analyze end.
`--input  input.yuv -s 1280x720 -f 100 --output /dev/null -v 6 -t 1  -p 1 --bitrate 600k`
It'll also crash when using constant QP.
And when using multi-threads, it'll not crash.

**Comment by adamjw24** [comment]
For me, I seem to get a deadlock after the last frame is pre-processed. Will look into it.

**Comment by zhijie1996** [comment]
> For me, I seem to get a deadlock after the last frame is pre-processed. Will look into it.

Thank you for quick reply. Yeah, sometimes it will also get a deadlock.

**Comment by adamjw24** [comment]
As a workaround while we fix it, use either `-t 0` or `-t 2` (or more)
