### ISSUE TITLE
New Feature testing

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#299]
Hi i like to know how to use FPPlinesSynchro feature to speed up encoding, i can use 36 threads, can u show me?

Regards

**Comment by adamjw24** [comment]
Use `vvencapp --preset faster <IO and coding options> --additional FPPLinesSynchro=1 -t <many threads>`.

`FPPLinesSynchro` works better for higher resolutions. For now it only works with constant QP coding (QPA is also ok, but no rate control) and preset only `faster`.
