### ISSUE TITLE
does vvenc support AVX512(AVX3) now?

### ISSUE THREAD

**Issue by gaaa1** [fraunhoferhhi/vvenc#301]
Hi, 
I'm doing some research on coding tools using vvenc1.8.0. And I tried to force AVX512 to be enabled to support my code by `#define USE_AVX512`, but compilation failed. I'd like to know if version1.8.0 or the latest version supports AVX512 now? 
Regards

Environment
OS: Windows11 22621.1992
Compiler: MSVC16.35
CPU: 12700k(only performance cores are used)

**Comment by adamjw24** [comment]
No, VVenC does not support AVX512.

There is no support planned. In that sense our roadmap is aligned with Intels roadmasp for their chips in that regards.

**Comment by gaaa1** [comment]
Thank for your reply!
This is my first question&message on github.

**Comment by adamjw24** [comment]
Welcome to GitHub
