### ISSUE TITLE
Unknown encoder x265

### ISSUE THREAD

**Issue by Zanzibarr** [fraunhoferhhi/vvenc#302]
After following the steps provided in [this guide](https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration), the command "ffmpeg -i in_file.y4m -c:v libx265 -g 1 out_file.mp4" stopped working: "Unknown encoder 'libx265' ".
I found the same issue with the libx264, but managed to solve it thanks to [this guide](https://stackoverflow.com/questions/9764740/unknown-encoder-libx264) (the one with the ./configure).
Is there a way to fix the problem for the libx265 that's similar to the one i found for the libx264?

**Comment by lehmann-c** [comment]
The wiki is only showing how to add the vvc codec.
It´s up to you what other codecs you want to add to your ffmpeg build.

It´s also written in the guide in the configure step:
`Add more options to your configure command to enable all needed tools and codecs`

To add other codecs, follow the general [FFmpeg CompilationGuide ](https://trac.ffmpeg.org/wiki/CompilationGuide)

**Comment by Zanzibarr** [comment]
Thanks, i found the problem. Now it works
