### ISSUE TITLE
coding vvc for best psnr and ssim value

### ISSUE THREAD

**Issue by Diyari90** [fraunhoferhhi/vvenc#305]
thanks for your answer me.

a) I encode my .y4m video to h266 by this command line (ffmpeg -i <input> -c:v vvc -b:v 20M -qp 0 -preset faster <output>)
b) i want to psnr the video encoded with my y4m but the result is (17.6...) not as i expecting it c) i have warning in timebase difference i fixed in h265,264 by this (-vsync 0 -enc_time_base -1 -video_track_timescale 60) this parameter not work in vvc not know why it warning me -vysnc is deprecated you should use (-fps_mode ), then i will change my command line to this  ( -fps_mode vfr  -enc_time_base -1 -video_track_timescale 60) still i get same warning my time base deffrente frist input 1/12000 and second input is 1/60.

i searched on internet and looked at those issue in GitHub i couldn't resolve my problem i didn't got anything so i hope answering my 3 issue i wrote it

**Comment by jungleboynx** [comment]
The qp value is approximately the B-SLICE quantizer. The I-SLICE is about 10 lower which means the lowest qp is about 10 if that's any help. It's not possible to create lossless Intra frames only like x264 or x265.

**Comment by Diyari90** [comment]
@jungleboynx  the bitrate isn't any problem i will just remove it and left it for default ,my problem is when i do psnr and ssim it give me less value like raw video and encoding is deferent video

**Comment by adamjw24** [comment]
> a) I encode my .y4m video to h266 by this command line (ffmpeg -i -c:v vvc -b:v 20M -qp 0 -preset faster )

VVenC does not really support lossless encoding, so `-qp 0`, while being a valid parameter values, is not a good choice. I'd say with qp >= 15 you would start getting meaningful results. Below that we are currently looking into improving near-lossless quality.

> b) i want to psnr the video encoded with my y4m but the result is (17.6...) not as i expecting it

Could you elaborate. This does not make much sense
