### ISSUE TITLE
Contradictory condition that can fail with some compilation options

### ISSUE THREAD

**Issue by vrabaud** [fraunhoferhhi/vvenc#309]
THis condition checks for a value and its negation. What should it be?
https://github.com/fraunhoferhhi/vvenc/blob/592adf1a2da818a07249024a43fc8fff559d4f26/source/Lib/EncoderLib/VLCWriter.cpp#L1866

**Comment by adamjw24** [comment]
Guess thats an `if( false )`

Good catch, we'll have a look
