### ISSUE TITLE
HDR

### ISSUE THREAD

**Issue by phanluchoafptpoly** [fraunhoferhhi/vvenc#319]
Hello, 

Is there any guide for keep HDR Information when encode VVC ?

Thanks!

**Comment by lehmann-c** [comment]
When the input contains any HDR/SDR information as colorspace, primaries, transform matrix they are automatically kept and written into the bitstream.
If the input does not contain any information (e.g. RAW video) it can be set by using the vvenc-params section.
The wiki will show you how it can be set:
https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#hdr-and-sdr-signalization-for-raw-input

**Comment by phanluchoafptpoly** [comment]
> When the input contains any HDR/SDR information as colorspace, primaries, transform matrix they are automatically kept and written into the bitstream. If the input does not contain any information (e.g. RAW video) it can be set by using the vvenc-params section. The wiki will show you how it can be set: https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#hdr-and-sdr-signalization-for-raw-input

Thanks a lot!
