### ISSUE TITLE
Unicode format issue in file "BitAllocation.cpp"

### ISSUE THREAD

**Issue by starxiang** [fraunhoferhhi/vvenc#33]
Hello, 

When I want to build a Visual Studio 2019 solution of VVenC, after the solution generated and i build the "vvencapp" project and  it turned out to be failed, for the reason that an error happened in file "BitAllocation.cpp"

`'warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss`

and I solved this by save this file in the format of "UNICODE codepage 1200" instead of "Unicode (UTF-8 without signature) - Codepage 65001", then it can build successfully.

I don't know whether it can be regarded as a bug or what

**Comment by adamjw24** [comment]
I cannot reproduce it locally, but this doesn't mean its not an issue. Seems like something that has to do with localization settings on a specific computer.

I looked through the file and don't see any strange characters. In some files we still have german comments with special characters, but apparently not in this one. 

Could you diff the file before and after the change? All characters seem to be ASCII representable, so they should stay the same when changing the Unicode flavor.

**Comment by adamjw24** [comment]
I actually did try the test and changed the encoding from UTF-8 w/o sig. to ANSI, and this does not produce a diff, as expected. I would expect the problem to be with the Git settings. Could you try downloading the release archive and building from there?

https://github.com/fraunhoferhhi/vvenc/archive/refs/tags/v0.3.1.0.zip

**Comment by starxiang** [comment]
Sorry for my late response, the merge above solved this problem, This was caused by the quotation mark, thank you all @adamjw24 and @jbrdbg
