### ISSUE TITLE
Print encode progress in one line instead of one line per encoded frame

### ISSUE THREAD

**Issue by Simulping** [fraunhoferhhi/vvenc#335]
As the title says, it would be better if VVenC were to print its progress in a single line like all other encoders do (x264, x265, vpxenc, etc) instead of just printing new ones one after another.

![Screenshot_20231128_182934](https://github.com/fraunhoferhhi/vvenc/assets/12994794/4509388f-6d59-4c22-bd77-5646553a4eb7)

**Comment by adamjw24** [comment]
While I guess your request is valid, did you try playing around with verbosity settings?

Per default one line will be printed per second of encoded input. I'm sure this could be made into incremental progress within a single line with a simple `sed` script.

You and everyone else is invited to take on this issue, though.

**Comment by Simulping** [comment]
@adamjw24 I did play around with the verbosity setting for a bit yeah.
