### ISSUE TITLE
Brew install method doesn't work

### ISSUE THREAD

**Issue by martystack** [fraunhoferhhi/vvenc#337]
When following the instructions here:

https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#macos

FFMPEG cannot find the encoder / decoder

(base) martinstack@Martins-Mac-Pro-Late-2013 ffmpeg % brew install vvdec vvenc
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################### 100.0%
Warning: vvdec 2.1.3 is already installed and up-to-date.
To reinstall 2.1.3, run:
  brew reinstall vvdec
Warning: vvenc 1.9.1 is already installed and up-to-date.
To reinstall 1.9.1, run:
  brew reinstall vvenc
(base) martinstack@Martins-Mac-Pro-Late-2013 ffmpeg % ffmpeg -hide_banner -codecs | grep vvc
 ..V.L. vvc                  H.266 / VVC (Versatile Video Coding)
(base) martinstack@Martins-Mac-Pro-Late-2013 ffmpeg % ffmpeg -h encoder=libvvenc            
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with Apple clang version 14.0.0 (clang-1400.0.29.202)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/6.0_1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Codec 'libvvenc' is not recognized by FFmpeg.

**Comment by lehmann-c** [comment]
The ffmpeg installation folder seems to be the default ffmpeg installation that you installed via homebrew (`--prefix=/usr/local/Cellar/ffmpeg/6.0_1`) 
Please check you environment variables.
If you install ffmpeg in the way it is described in the wiki, the local ffmpeg version containing vvenc/vvdec should be installed in `/usr/local/bin/ffmpeg`
The configuration must contain `--enable-libvvdec --enable-libvvenc` otherwise you are using the wrong ffmpeg installation.

**Comment by adamjw24** [comment]
Will close in a few days if no feedback.
