### ISSUE TITLE
Abbreviations in the article

### ISSUE THREAD

**Issue by birdie-github** [fraunhoferhhi/vvenc#357]
You've got a nice article https://github.com/fraunhoferhhi/vvenc/wiki/Encoder-Performance but it has a ton of abbreviations.

Would be great if you explained them in a new separate section of it.

Thank you!

**Comment by adamjw24** [comment]
Good point, we'll put some effort to make it more accessible soon.

**Comment by lehmann-c** [comment]
> You've got a nice article https://github.com/fraunhoferhhi/vvenc/wiki/Encoder-Performance but it has a ton of abbreviations.
> 
> Would be great if you explained them in a new separate section of it.
> 
> Thank you!

Can you specify what abbreviations do you mean in particular?
There are already quite a lot of references on the bottom where the main topics are cross references.
