### ISSUE TITLE
The difference between presets

### ISSUE THREAD

**Issue by birdie-github** [fraunhoferhhi/vvenc#359]
Both x264 and x265 have very nice tables presenting the difference between presets:

https://dev.beandog.org/x264_preset_reference.html
https://x265.readthedocs.io/en/master/presets.html

It would be nice to see/get something like that for vvenc, along with an explanation which preset is suitable for which common tasks and whether using "slower" makes any sense at all because it's extremely slow (slower than 0.2fps for 4K video for Ryzen 7 5800X, i.e. for a 60fps video that's going to be > 300 times slower than realtime).

**Comment by lehmann-c** [comment]
There is a new [Presets](https://github.com/fraunhoferhhi/vvenc/wiki/Presets) section in our wiki concerning the preset option:
Feel free to have a look.

**Comment by birdie-github** [comment]
Amazing, thanks a ton!
