### ISSUE TITLE
why not release the exe?

### ISSUE THREAD

**Issue by kucingkembar** [fraunhoferhhi/vvenc#366]
sorry for a newbie question,
why not release the exe like gyan.dev & BtbN?
a newbie like me have a difficult to use (C)Make software

**Comment by adamjw24** [comment]
What even is gyan.dev and BtbN?

Once you release an .exe (for which windows even, using which compiler etc...), you need to start releasing binaries for linux, unix, arm, mac. The list is endless... The effort goes beyond what a small team like ours can do.

**Comment by kucingkembar** [comment]
i dont know what is should be called,
but if you like to download exe from "official"
https://www.ffmpeg.org/download.html
There 2 version : gyan.dev and BtbN

if not troublesome, can you make it for me please?

**Comment by adamjw24** [comment]
You just said it. There is now "official" way to download ffmpeg exe. There are only "inofficial" websites.

This is troublesome. We will not be distributing binaries. But if anyone else reading this wants to share, please feel free.

**Comment by adamjw24** [comment]
I'll reopen it for a few days, so ppl have a chance to read it and share with you.

**Comment by kucingkembar** [comment]
sorry if i rude, i close it now
![Untitled](https://github.com/fraunhoferhhi/vvenc/assets/47294266/3a44fa43-4f0e-49c0-9334-623b7d2834db)

**Comment by birdie-github** [comment]
If you'd spent a few minutes searching, you'd have found the binaries:

https://github.com/MartinEesmaa/VVCEasy
