### ISSUE TITLE
SAO default value in help message is 0 but in default preset it's 1

### ISSUE THREAD

**Issue by Mr-Z-2697** [fraunhoferhhi/vvenc#371]

**Comment by adamjw24** [comment]
By setting a preset you override the default (a preset in the end is just a set of options). This is true for quite some options, and considering our interface its impossible to really use the defaults of some options (you cannot initialize the encoder properly without setting the preset). Preset defaults is a different story, see issue #359 , we’ll describe those a bit better soon.

Don’t think to much about it, low-level tool configuration is really an expert setting and the default is there just to avoid uninitialized value problems with the compiler and sanitizer. Don’t read to much into it.

**Comment by Mr-Z-2697** [comment]
I know it's not really a big deal, but if I use simplest command line like `vvencffapp -i - --y4m -b NUL` SAO is still enabled by default.
I guess the preset is loaded by default, so it overrides the default value of options no matter what.

vvenc [verbose]: CODING TOOL CFG: CTU128 QTMin44BTT21 IBD:1 SAO:1 ALF:1 (NonLinLuma:0 NonLinChr:0) CCALF:1 Tiles:1x1 Slices:1 WPP:0 WPP-Substreams:1 TMVP:1 DQ:1 SDH:0 CST:1 BDOF:1 DMVR:1 MTSImplicit:1 SBT:0 JCbCr:1 CabacInitPresent:1 AMVR:5 SMVD:3 LMCS:2 (Signal:SDR Opt:0) CIIP:0 MIP:1 AFFINE:4 (PROF:1, Type:1) MMVD:3 DisFracMMVD:1 SbTMVP:1 GPM:3 LFNST:1 MTS:0 ISP:3 TS:2 TSLog2MaxSize:4 useChromaTS:0 BDPCM:2 IBC:2 BCW:0

**Comment by adamjw24** [comment]
As mentioned, it’s impossible to start the encoder without specifying the preset. Default preset is medium, and in preset medium SAO is set to 1.

**Comment by adamjw24** [comment]
I think this has been discussed and resolved as much as it can be. Closing.
