### ISSUE TITLE
Integration ffmpeg 7.0 Windows

### ISSUE THREAD

**Issue by F1EJP** [fraunhoferhhi/vvenc#372]
Hello
I try the same modification that ffmpeg 6.1.1 ffmpegPath=https://git.ffmpeg.org/ffmpeg.git#tag=n7.0 with no error of compilation
but at final libvvenc is not include.
Thanks for all.

**Comment by adamjw24** [comment]
It is very clearly stated which versions this works with.

See
* https://github.com/fraunhoferhhi/vvenc/issues/367
* https://github.com/fraunhoferhhi/vvenc/issues/361
