### ISSUE TITLE
Info for CQF

### ISSUE THREAD

**Issue by thx4ever** [fraunhoferhhi/vvenc#382]
Hi, can u show some examples How to use CQF mode?

Regards

**Comment by ZenKiyoshi** [comment]
@thx4ever I don't see any paramerters in `--fullhelp` yet. It would be for next version.


@adamjw24 Anyway I also want to ask: Does CQF work similarly to x264/x265 CRF?

**Comment by adamjw24** [comment]
CQF is similar to CRF in x265/x264, which means it is rate capped constant quality encoding.

Constant quality, i.e. `--qp XY --qpa 1`. Capped, i.e. `--maxrate YZ`. So thats the three params you use for CQF. `--qpa 1` is the default, so can be skipped.

Best, Adam

**Comment by thx4ever** [comment]
> CQF is similar to CRF in x265/x264, which means it is rate capped constant quality encoding.
> 
> Constant quality, i.e. `--qp XY --qpa 1`. Capped, i.e. `--maxrate YZ`. So thats the three params you use for CQF. `--qpa 1` is the default, so can be skipped.
> 
> Best, Adam

You mean --qp -qpa 1 --MaxBitrate?

**Comment by adamjw24** [comment]
> You mean --qp -qpa 1 --MaxBitrate?

No, I mean `--qp A --qpa 1 --maxrate B`, thats for `vvencapp` tho. For the `vvencFFapp` the params are different.

**Comment by thx4ever** [comment]
Im currently using vvencFFapp can u show me how to do it?

Regards

**Comment by adamjw24** [comment]
> You mean --qp -qpa 1 --MaxBitrate?

For `vvencFFapp`, `--QP=A -qpa 1 --MaxBitrate=B` (`-qpa 1` is the same as `--PerceptQPA=1`) seems the way to go. Mind that `-qpa 1` is not the default, so this has to be specified.
