### ISSUE TITLE
Encoding 65 frames with intra period 32 gives only 2 IRAP frames

### ISSUE THREAD

**Issue by bart-kroon** [fraunhoferhhi/vvenc#390]
Hi all, I have a question and it may be related to #311 .

For MPEG experiments we use 65 frames with an intra period 32 to have three I-frames. When upgrading from VVenC 1.7.0 to 1.11.1, the final frame is now a B-frame (STSA). I suppose this is intended behavior, but is there a way to convince vvencFFapp to output three I-frames like before?

This is a current log-file for context: [TMIV_A65_B02_RP4_geo_c00.log](https://github.com/user-attachments/files/15883150/TMIV_A65_B02_RP4_geo_c00.log).
The structure in decoding order is: 31:IDR_W_RADL, RADL..., 63: IDR_W_RADL, RADL..., 64: STSA
(I switched DecodingRefreshType from 1 to 2 for testing. In both cases the STSA is there.)

This is from a previous experiment with VVenC 1.7.0: [TMIV_A65_B02_RP4_geo_c00.log](https://github.com/user-attachments/files/15883161/TMIV_A65_B02_RP4_geo_c00.log).
The structure in decoding order is: 0:IDR_N_LP, 32:CRA, RASL..., 64:CRA, RASL...

**Comment by adamjw24** [comment]
You have to specify `--POC0IDR`, which forces the old behavior.

Best, Adam

**Comment by bart-kroon** [comment]
I'll try. Thanks for the hint.
