### ISSUE TITLE
Setting or controlling quality of layers in VVC multi-layer encoding 

### ISSUE THREAD

**Issue by prtsh** [fraunhoferhhi/vvenc#4]
VVC, like the predecessor, supports multi-layer encoding. I looked into the config files provided in the base VTM repo along with this repo, and couldn't find a way to set the quality of the layers independently. I read the software manually, but couldn't find any information.

Is there a way to specify the quality of enhancement layers during encoding. For example, L0 at 32 and L1 at 33, and with L2 at 35.

<Not exactly an issue, thanks for the help!>

**Comment by adamjw24** [comment]
For the moment our goal is to support best possible quality at a manageable time for the main10 profile. Multi-layer support is a special-case requiring a different profile, so it is not supported for now. Regarding how there is still a lot of stuff to support in the main10 profile, this is what we will concentrate on in the near future.
