### ISSUE TITLE
Segfaults using FGA with certain resolutions

### ISSUE THREAD

**Issue by 6ws** [fraunhoferhhi/vvenc#400]
When film grain analysis is enabled, using non-mod 8 resolutions such as 1920x804 will cause a segmentation fault upon encoding.

**Comment by trixoniisama** [comment]
I have had segfaults happen to me after a few hundred frames with 1920x1080 sources, so it's definitely not just related to that. Simply disabling FGA would fix the segfault and the entire video would encode normally.

**Comment by vigneshvijay03** [comment]
@trixoniisama, Could you please provide the sequence and settings you used when you encountered the segmentation faults so that we can replicate the issue and work towards a solution? Thank you.

**Comment by trixoniisama** [comment]
Seemingly fixed with the above commit, thanks!
