### ISSUE TITLE
VVenc produces a different bitstream when integrated into ffmpeg

### ISSUE THREAD

**Issue by hassount** [fraunhoferhhi/vvenc#401]
I am trying to test VVenc integrated within the ffmpeg framework and I am facing the issue that the bitstreams generated from ffmpeg are larger than the bitstreams generated by VVencapp without causing a difference in the decoded video. 

**Version**
v1.12.0

**Command lines used:** 
`./ffmpeg  -f rawvideo -pix_fmt yuv420p -s:v 352x288 -r 30000/1001 -i ~/stream/akiyo_cif.yuv -vcodec libvvenc -vvenc-params internalbitdepth=8:intraperiod=500:qp=63:threads=0 -vf format=yuv420p -strict experimental output_ffmpeg.266`

`./vvencapp -i ~/stream/akiyo_cif.yuv --size 352x288  --format  yuv420 --internal-bitdepth 8  --fps 30000/1001 --intraperiod 500 --qp 63 --threads 0  -o output_vvenc.266`

Some of the difference is there seems to be a repeating "28 00 00 01 00" string for every frame. 

Any thoughts on how to disable this diff so that the bitrate is not penalized for ffmpeg ?

**Comment by hassount** [comment]
Tracked the difference to accessunitdelimiter which seems to be off by default in vvencapp and on by default in ffmpeg. setting accessunitdelimiter=0 in the ffmpeg allows me to get the same bitstream. 

Not sure if this is considered an issue or not, so I am gonna leave this issue open for now. Maintainers can feel free to close the issue should it be deemed expected.

**Comment by lehmann-c** [comment]
In ffmpeg  this options needs not be enabled, since the output is usually a container (mp4,ts).   
Transport Stream for instance needs the AccessUnitDelimiter flag to be present to create valid streams.   
As the vvencapp only support RAW bitstream output it is disabled by default.
