### ISSUE TITLE
VVenC 1.12 4:0:0 monochome

### ISSUE THREAD

**Issue by jungleboynx** [fraunhoferhhi/vvenc#402]
I was wondering why 4:0:0 was added in VVenC 1.12 as it's possible to encode monochome in 4:2:0 mode with very little difference in filesize. Maybe it's to stop synthetic grain from being created in the UV fields when FGS support becomes available.

I was looking at the Intel Xe GPU decode capability and realised that Intel Xe can only decode AV1 4:2:0 at present so they must have got around the problem of preventing synthetic grain from being created in the UV fields when monochrome content is used. It's possible that the AV1 film grain is re-constituted by the graphics driver and not the GPU.

If the UV fields are blank then FGS only applies to the Y field but the problem is how do you know the UV fields are blank if 4:0:0 mode isn't available. I was wondering how they got around this problem with AV1 film grain. The same problem effects VVenC except you now have 4:0:0 mode.

**Comment by adamjw24** [comment]
Monochrome support was always present in VVenC, but not in the app interface, and also buggy. We just had someone need it so we fixed the two minor issues. It has nothing to do with FGS.

And possibly doing monochrome as 420 is not very inefficient, but it's not up to us to dictate people's use cases.
