### ISSUE TITLE
ffmpeg - Should the vvc decoder be experimental but not the enocder?

### ISSUE THREAD

**Issue by JohnTravolski** [fraunhoferhhi/vvenc#404]
I noticed the ffmpeg integration page now states:

> "VVenC is officially supported in FFmpeg since 15th June 2024 (revision c75940db29)."

I downloaded the latest windows build from here (version: 2024-07-10-git-1a86a7a48d): https://www.gyan.dev/ffmpeg/builds/ to give it a shot.

I noticed I could encode using vvenc with no issues, but as soon as I tried to decode it, I would get an error:

`"The decoder 'vvc' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it."`

**Is it expected that I would receive this message for decoding but not for encoding? Why? Any idea how long it will be kept as experimental?**

**Comment by adamjw24** [comment]
As correctly noted in the title this question concerns ffmpeg and their policies. We have no information, or influence, on what the developers of ffmpeg deem experimental and what not. The decoding part of your question has zero relation to our projects. Closing.
