### ISSUE TITLE
A question about MCTF

### ISSUE THREAD

**Issue by liqingzhaomingcheng** [fraunhoferhhi/vvenc#408]
First of all, thank you very much for developing such an excellent video encoder. 
The question I want to ask is about MCTF. I noticed that there is a module called applyPlanarCorrectionCore in MCTF for deblocking. I would like to ask if there are any related papers or articles about the algorithm used by this module. 
Thank you very much！

**Comment by crhelmrich** [comment]
Hi and thanks for your interest! Unfortunately, we haven't had the time yet for a scientific publication on the planar correction, which simply intends to reduce blocking during the non-overlapping block-wise MCTF operation by compensating for strong luma gradients within each block prior to the bilateral denoising filter.

I hope that helps for now. I'll try to update this post later with a visualization.

Christian

**Comment by liqingzhaomingcheng** [comment]
> Hi and thanks for your interest! Unfortunately, we haven't had the time yet for a scientific publication on the planar correction, which simply intends to reduce blocking during the non-overlapping block-wise MCTF operation by compensating for strong luma gradients within each block prior to the bilateral denoising filter.
> 
> I hope that helps for now. I'll try to update this post later with a visualization.
> 
> Christian

Got it, thanks for your reply！

**Comment by liqingzhaomingcheng** [comment]
> Hi and thanks for your interest! Unfortunately, we haven't had the time yet for a scientific publication on the planar correction, which simply intends to reduce blocking during the non-overlapping block-wise MCTF operation by compensating for strong luma gradients within each block prior to the bilateral denoising filter.
> 
> I hope that helps for now. I'll try to update this post later with a visualization.
> 
> Christian

I apologize for bothering you again. I tried to conduct a switch test on this module and found that the gain brought by this module seems to be quite small. I would like to ask how much objective or subjective gain this module provides.
