### ISSUE TITLE
no vvEnc with current instruction (ffmpeg 7.0)

### ISSUE THREAD

**Issue by lhksoft** [fraunhoferhhi/vvenc#416]
I followed the instruction for m-ab-s, only VVDec is integrated in ffmpeg, no VVEnc. The patch seems to fail.
So what to do now ?

```
ffmpeg version N-116754-gb7952bf9db-g507c2a5774+2 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
configuration:  --pkg-config=pkgconf --cc='ccache gcc' --cxx='ccache g++' --ld='ccache g++' --extra-cxxflags=-fpermissive --extra-cflags=-Wno-int-conversion --disable-autodetect --enable-amf --enable-bzlib --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-iconv --enable-lzma --enable-nvenc --enable-zlib --enable-sdl2 --enable-ffnvcodec --enable-nvdec --enable-cuda-llvm --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libdav1d --enable-libaom --disable-debug --enable-libfdk-aac --enable-fontconfig --enable-libass --enable-libbluray --enable-libfreetype --enable-libharfbuzz --enable-libmfx --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libshine --enable-gpl --enable-avisynth --enable-libxvid --enable-libopenmpt --enable-version3 --enable-librav1e --enable-libsrt --enable-libgsm --enable-libvmaf --enable-libsvtav1 --enable-chromaprint --enable-decklink --enable-frei0r --enable-libaribb24 --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfribidi --enable-libgme --enable-libilbc --enable-libsvthevc --enable-libkvazaar --enable-libmodplug --enable-librist --enable-librtmp --enable-librubberband --enable-libtesseract --enable-libxavs --enable-libzmq --enable-libzvbi --enable-openal --enable-libcodec2 --enable-ladspa --enable-libglslang --enable-vulkan --enable-libdavs2 --enable-libxavs2 --enable-libuavs3d --enable-libplacebo --enable-libjxl --enable-opencl --enable-opengl --enable-libopenh264 --enable-openssl --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DCACA_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCHROMAPRINT_NODLL --extra-cflags=-DZMQ_STATIC --extra-libs=-lpsapi --extra-cflags=-DLIBXML_STATIC --extra-libs=-liconv --disable-w32threads --extra-cflags=-DKVZ_STATIC_LIB --enable-nonfree --extra-cflags=-DAL_LIBTYPE_STATIC --extra-cflags='-IC:/mabs/local64/include' --extra-cflags='-IC:/mabs/local64/include/AL'
libavutil      59. 34.100 / 59. 34.100
libavcodec     61. 11.100 / 61. 11.100
libavformat    61.  5.101 / 61.  5.101
libavdevice    61.  2.100 / 61.  2.100
libavfilter    10.  2.102 / 10.  2.102
libswscale      8.  2.100 /  8.  2.100
libswresample   5.  2.100 /  5.  2.100
libpostproc    58.  2.100 / 58.  2.100

>ffmpeg -hide_banner -codecs | grep vvc
 D.V.L. vvc                  H.266 / VVC (Versatile Video Coding) (decoders: vvc vvc_qsv)
```

When issuing the patch, I get this (error?) message : 
```
Add-support-for-H266-VVC.patch
  Patch could not be applied with `git am`...

```

Tx for any help.

**Comment by Equadex** [comment]
Did you check out ffmpeg n7.0.2? I followed the instructions on the wiki page for both vvenc and vvdec without difficulty.

**Comment by lehmann-c** [comment]
VVdeC is not integrated in your FFmpeg build - the vvc decoder that is visible in your log is the internal ffmpeg vvc decoder (ffvvc).   
The latest official ffmpeg patch for VVdeC cannot be applied anymore to the master. That´s why you see that error message:  
`Add-support-for-H266-VVC.patch`  
`  Patch could not be applied with `git am`...`  

We updated our VVdeC Wiki for m-ab-s integration with an updated patch that can be applied to the master. Please have a look at:
https://github.com/fraunhoferhhi/vvdec/wiki/FFmpeg-Integration

The new patch is:
https://raw.githubusercontent.com/wiki/fraunhoferhhi/vvdec/data/patch/v6-0001-avcodec-add-external-dec-libvvdec-for-H266-VVC.patch

VVenC should be build and available in FFmpeg as soon you are enabling vvenc/vvdec support:  
Please check if it is available in the `ffmpeg_options_full` in the file `media-autobuild_suite.bat`  
and in `media-autobuild_suite.ini` vvenc and vvdec should be set to 1:
`vvenc=1`  
`vvdec=1`  

Please be aware that, when asking for `VVC Reference Software` support, vvenc/vvdec are not automatically enabled! There are independent options for VVenC and VVdeC.

**Comment by lhksoft** [comment]
Tx, it worked fine.

When I test ffmpeg for 'codecs', now I get :
`DEV.L. vvc                  H.266 / VVC (Versatile Video Coding) (decoders: vvc libvvdec vvc_qsv) (encoders: libvvenc)
`
Seems to be okay now.

From your wiki, I don't understand how I can build a previous version of ffmpeg using m-ab-s. Could you explain that to me, like if I wish to compile ffmpeg-n6.1.1 with VVenc and VVdec? I appreciate it if you can.

**Comment by lehmann-c** [comment]
Great that it finally worked.  

Using an old tag won´t be an easy one as all dependencies are using the master.  
You can do it by setting a specific tag in the file  `build/media-autobuild_suite.ini`. For instance:   
`ffmpegPath=https://git.ffmpeg.org/ffmpeg.git#tag=n6.1.1`.   

But it´ll be a mess to find the corresponding tags for each single repository to be aligned to tag n6.1.1.  
Especially for vvenc/vvdec the current patches will not work.  
As ffmpeg is patched for other codecs as well in the m-ab-s scripts, it won´t work.

**Comment by lhksoft** [comment]
Yeah, I already figured that out. It just won't work. Apparently m-ab-s only is for the latest 'master' build. If I want to have a previous build I must compile using [ffmpeg-windows-build-helpers](https://github.com/rdp/ffmpeg-windows-build-helpers) which does a cross-compile in a real linux system. But then I don't have the goodies like vvenc/vvdec.

Tx for your assistance. I hope current solution will keep working in future versions of ffmpeg.
