### ISSUE TITLE
pkgconfig directory and libvvenc.pc file missing when installing in MinSizeRel mode

### ISSUE THREAD

**Issue by meetviolet** [fraunhoferhhi/vvenc#435]
Win10, VS2022, CMake 3.28.1, vvenc 1.12.0.

Pkgconfig directory contains `libvvenc.pc` is required when compiling ffmpeg with `--enable-libvvenc`. But it is omitted during  MinSizeRel mode, both static and shared builds installing. Debug mode install works fine. I think it might be sth. missing in MinSizeRel mode installing.

**Comment by lehmann-c** [comment]
Should working now when using the master, after fixing [issue 434](https://github.com/fraunhoferhhi/vvenc/pull/434).
What build commands did you use?

in principle following command is working:
`cmake -S . -B build/release-shared -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_SHARED_LIBS=1`
`cmake --build build/release-shared -j`
`sudo cmake --build build/release-shared --target install`

**Comment by meetviolet** [comment]
Haven't tried the master branch yet. Maybe tomorrow. I built 1.12.0 released code (behand the master branch) on Win10 using cmake-gui generated Visual Studio solution. Have you tried static MinSizeRel build? The old code I tried failed both static and shared builds.

**Comment by lehmann-c** [comment]
As you reported the issue #432 where install did not work for MinSizeRel and the issue was fixed and closed (#434) this should work properly now when using the master.
