### ISSUE TITLE
MacOS M2 ffmpeg + vvenc build fails due to undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by BrytonLee** [fraunhoferhhi/vvenc#445]
# make 
LD      libswscale/libswscale.8.dylib
ld: warning: -single_module is obsolete
Undefined symbols for architecture arm64:
  "_av_calloc", referenced from:
      _ff_init_filters in slice.o
      _ff_init_filters in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      _alloc_slice in slice.o
      ...
  "_av_fast_malloc", referenced from:
      _scale_internal in swscale.o
      _scale_internal in swscale.o
  "_av_fast_realloc", referenced from:
      _ff_range_add in utils.o
  "_av_frame_alloc", referenced from:
      _sws_init_context in utils.o
      _sws_init_context in utils.o
  "_av_frame_free", referenced from:
      _sws_freeContext in utils.o
      _sws_freeContext in utils.o
  "_av_frame_get_buffer", referenced from:
      _sws_frame_start in swscale.o
      _sws_scale_frame in swscale.o
  "_av_frame_ref", referenced from:
      _sws_frame_start in swscale.o
      _sws_frame_start in swscale.o
      _sws_scale_frame in swscale.o
      _sws_scale_frame in swscale.o
  "_av_frame_unref", referenced from:
      _sws_frame_end in swscale.o
      _sws_frame_end in swscale.o
      _sws_frame_start in swscale.o
      _sws_scale_frame in swscale.o
      _sws_scale_frame in swscale.o
      _sws_scale_frame in swscale.o
  "_av_free", referenced from:
      _sws_freeContext in utils.o
      _sws_freeVec in utils.o
      _sws_freeFilter in utils.o
      _sws_freeFilter in utils.o
      _sws_freeFilter in utils.o
      _sws_freeFilter in utils.o
      _sws_freeFilter in utils.o
      ...
  "_av_freep", referenced from:
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      _ff_free_filters in slice.o
      ...
  "_av_get_bits_per_pixel", referenced from:
      _sws_setColorspaceDetails in utils.o
      _sws_setColorspaceDetails in utils.o
      _sws_init_single_context in utils.o
      _sws_init_single_context in utils.o
  "_av_get_cpu_flags", referenced from:
      _rgb2rgb_init_aarch64 in rgb2rgb.o
      _ff_sws_init_swscale_aarch64 in swscale.o
      _ff_get_unscaled_swscale_aarch64 in swscale_unscaled.o
      _sws_init_single_context in utils.o
  "_av_get_pix_fmt_name", referenced from:
      _rgbToRgbWrapper in swscale_unscaled.o
      _rgbToRgbWrapper in swscale_unscaled.o
      _planarRgbToRgbWrapper in swscale_unscaled.o
      _planarRgbToRgbWrapper in swscale_unscaled.o
      _planarRgbaToRgbWrapper in swscale_unscaled.o
      _planarRgbaToRgbWrapper in swscale_unscaled.o
      _rgbToPlanarRgbWrapper in swscale_unscaled.o
      _rgbToPlanarRgbWrapper in swscale_unscaled.o
      ...
  "_av_image_alloc", referenced from:
      _sws_setColorspaceDetails in utils.o
      _OUTLINED_FUNCTION_6 in utils.o
  "_av_log", referenced from:
      _ff_sws_init_range_convert_aarch64 in swscale.o
      _OUTLINED_FUNCTION_0 in swscale.o
      _OUTLINED_FUNCTION_0 in alphablend.o
      _OUTLINED_FUNCTION_0 in hscale.o
      _ff_sws_init_input_funcs in input.o
      _ff_sws_init_output_funcs in output.o
      _OUTLINED_FUNCTION_1 in output.o
      ...
  "_av_malloc", referenced from:
      _ff_init_gamma_convert in gamma.o
      _ff_init_desc_fmt_convert in hscale.o
      _ff_init_desc_hscale in hscale.o
      _ff_init_desc_cfmt_convert in hscale.o
      _ff_init_desc_chscale in hscale.o
      _ff_init_filters in slice.o
      _alloc_lines in slice.o
      _alloc_lines in slice.o
      ...
  "_av_malloc_array", referenced from:
      _initFilter in utils.o
      _initFilter in utils.o
      _initFilter in utils.o
      _OUTLINED_FUNCTION_12 in utils.o
  "_av_mallocz", referenced from:
      _sws_setColorspaceDetails in utils.o
      _sws_setColorspaceDetails in utils.o
      _alloc_set_opts in utils.o
      _sws_alloc_context in utils.o
      _sws_getContext in utils.o
      _sws_getCachedContext in utils.o
      _ff_init_vscale in vscale.o
      _ff_init_vscale in vscale.o
      ...
  "_av_opt_copy", referenced from:
      _sws_init_context in utils.o
  "_av_opt_get_int", referenced from:
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
  "_av_opt_set_defaults", referenced from:
      _sws_setColorspaceDetails in utils.o
      _sws_setColorspaceDetails in utils.o
      _alloc_set_opts in utils.o
      _sws_alloc_context in utils.o
      _sws_getContext in utils.o
      _sws_getCachedContext in utils.o
  "_av_opt_set_int", referenced from:
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
      _sws_getCachedContext in utils.o
  "_av_pix_fmt_desc_get", referenced from:
      _ff_sws_init_range_convert_aarch64 in swscale.o
      _ff_hscale16to15_4_neon in swscale.o
      _ff_hscale16to15_4_neon in swscale.o
      _ff_hscale16to19_4_neon in swscale.o
      _ff_hscale16to19_4_neon in swscale.o
      _ff_hscale16to15_X8_neon in swscale.o
      _ff_hscale16to15_X8_neon in swscale.o
      ...
  "_av_pix_fmt_get_chroma_sub_sample", referenced from:
      _sws_init_single_context in utils.o
      _sws_init_single_context in utils.o
  "_av_pix_fmt_swap_endianness", referenced from:
      _sws_init_single_context in utils.o
  "_avpriv_slicethread_create", referenced from:
      _sws_init_context in utils.o
  "_avpriv_slicethread_execute", referenced from:
      _sws_receive_slice in swscale.o
  "_avpriv_slicethread_free", referenced from:
      _sws_freeContext in utils.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libswscale/libswscale.8.dylib] Error 1

**Comment by adamjw24** [comment]
This is not related to vvenc

**Comment by BrytonLee** [comment]
> This is not related to vvenc

Thanks for your quick reply. I'll file this bug to FFmpeg project.
