### ISSUE TITLE
Any plans for YUV444 and higher bit depths?

### ISSUE THREAD

**Issue by bootcap** [fraunhoferhhi/vvenc#450]
I noticed that vvenc currently only supports YUV420 8-bit and YUV420 10-bit formats. I'm curious about the technical rationale behind this limitation and would like to know if there are any plans to implement support for **YUV444** and higher bit depth like **12bit or 16bit**？

These formats are particularly important for HDR content and professional video workflows where high color fidelity is crucial. Is this limitation due to:
    Current VVC/H.266 specification constraints?
    Performance considerations?

I would appreciate any insights into this and whether support for these formats is planned for future releases. Thank you!

**Comment by adamjw24** [comment]
There is no plan to support YUV444. Please mind that VVenC also support YUV400 (monochrome) in both 8 and 10 bit.

High bit depth would require large-scale refactoring, which would make the code a mess and indeed cause performance problems.

The spec supports 12 and 16 bit as well as YUV444 alright.

**Comment by JohnTravolski** [comment]
It's too bad. I'd really like this. Are there any VVC encoders that support 444?
