### ISSUE TITLE
Unit testing of SIMD kernels

### ISSUE THREAD

**Issue by georges-arm** [fraunhoferhhi/vvenc#451]
When writing AArch64 Neon and SVE implementations for some of the MCTF kernels I noticed that it was quite easy to find cases (e.g. tail loops) which do not appear to be covered by the existing encoding tests run by CTest.

It doesn't appear that there are any existing unit tests for common kernels, so I was wondering if there was appetite to add such test cases to the library? I'd be happy to write test cases for some of the kernels that I have been looking at if you could let me know a preference in terms of test framework library or how best to integrate it with the existing test code?

Thanks!

**Comment by adamjw24** [comment]
If you want to write a simple test-suite... I would be reluctant to add external dependencies to the repo. It would need to have a license that allows us to just copy it into our repo, like we did with simde and the json library.

**Comment by adamjw24** [comment]
I will have a look as soon as I'm back from JVET next week. Sorry for the slow responsiveness atm.
