### ISSUE TITLE
Problems in pure c++ code (disable SIMD)

### ISSUE THREAD

**Issue by 9reyson** [fraunhoferhhi/vvenc#46]
When disabling SIMD with SIMD_ENABLE = 0, there are some problems in pure c++ code.
1. Firstly, compile error
The complie error can be fixed as follows:
![image](https://user-images.githubusercontent.com/8808377/114022849-c4dfec80-98a4-11eb-9626-bbe9f65016e4.png)
![image](https://user-images.githubusercontent.com/8808377/114022915-d923e980-98a4-11eb-9a23-31b66073c0e0.png)

2. Problems in AdaptiveLoopFilter::deriveClassificationBlk()
AdaptiveLoopFilter::deriveClassificationBlk() will make the two encoding streams with the same parameters different.

**Comment by 9reyson** [comment]
I found the problems about AdaptiveLoopFilter::deriveClassificationBlk() using this command:
--preset fast -s 416x240 -r 50  --frames 33 --qpa 0 -ip 32   --qp 37  -o str.bin -i E:\Seqs\BasketballPass_416x240_50.yuv

**Comment by adamjw24** [comment]
We'll look into it, thanks

**Comment by adamjw24** [comment]
Indeed, non-SIMD ALF classification has a concurrency problem. Thanks for reporting. Will fix soon
