### ISSUE TITLE
Error when building on Mac Os

### ISSUE THREAD

**Issue by patriceangot** [fraunhoferhhi/vvenc#461]
Hi all,
I have the following error when i try to build on Mac OS (15.0.1) with cmake 3.31.0 and clang 19.1.3. Any idea ?

    /opt/homebrew/opt/llvm/bin/clang -x c++ -fmessage-length\=181 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fcolor-diagnostics -Wno-trigraphs -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -Werror -Wall -Wno-deprecated-register -Wno-unused-const-variable -Wno-unknown-attributes @/Users/angot/FFMPEG/vvenc/build/release-static/build/vvenc_arm_simd.build/Debug/Objects-normal/arm64/82b82416624d2658e5098eb0a28c15c5-common-args.resp -DUSE_NEON -MMD -MT dependencies -MF /Users/angot/FFMPEG/vvenc/build/release-static/build/vvenc_arm_simd.build/Debug/Objects-normal/arm64/Trafo_neon.d --serialize-diagnostics /Users/angot/FFMPEG/vvenc/build/release-static/build/vvenc_arm_simd.build/Debug/Objects-normal/arm64/Trafo_neon.dia -c /Users/angot/FFMPEG/vvenc/source/Lib/CommonLib/arm/neon/Trafo_neon.cpp -o /Users/angot/FFMPEG/vvenc/build/release-static/build/vvenc_arm_simd.build/Debug/Objects-normal/arm64/Trafo_neon.o
/Users/angot/FFMPEG/vvenc/source/Lib/CommonLib/arm/neon/Trafo_neon.cpp:254:27: error: implicit conversion loses integer precision: 'int64_t' (aka 'long long')
      to 'TCoeff' (aka 'int') [-Werror,-Wshorten-64-to-32]
  254 |       dstij[ 0 * line ] = shift_and_round( horizontal_add_s32x4( sum00 ), shift );
      |                         ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/angot/FFMPEG/vvenc/source/Lib/CommonLib/arm/neon/Trafo_neon.cpp:255:27: error: implicit conversion loses integer precision: 'int64_t' (aka 'long long')
      to 'TCoeff' (aka 'int') [-Werror,-Wshorten-64-to-32]
  255 |       dstij[ 1 * line ] = shift_and_round( horizontal_add_s32x4( sum01 ), shift );
      |                         ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by Jamaika1** [comment]
Fix doesn't work. What features need to be changed?
ffmpeg_avx.exe -v verbose -f concat -safe 0 -i mylist_v.txt -f concat -safe 0 -i mylist_a.txt -c:v libvvenc -vb 6000k -c:a aac -ac 2 -ar 48000 -ab 128k -movflags faststart -vf scale=1920:1080:in_range=full:out_range=full,format=yuv420p10le output_vvenc.vvc
```
[libvvenc @ 000001ce7f0ae8f0] libvvenc version: 1.12.1-0f7b70d
[libvvenc @ 000001ce7f0ae8f0] vvenc [notice]: Internal format                        : 1920x1080  29.97 Hz  SDR
vvenc [notice]: Threads                                : 8  (parallel frames: 4)
vvenc [notice]: Rate control                           : VBR  6 Mbps  single-pass
vvenc [notice]: Perceptual optimization                : Enabled
vvenc [notice]: Intra period (keyframe)                : 256
vvenc [notice]: Decoding refresh type                  : CRA
vvenc [notice]: Sequence PSNR output                   : Linear average only
vvenc [notice]: Hexadecimal PSNR output                : Disabled
vvenc [notice]: Sequence MSE output                    : Disabled
vvenc [notice]: Frame MSE output                       : Disabled
vvenc [notice]: Cabac-zero-word-padding                : Enabled
vvenc [notice]: Frame index                            : all frames
vvenc [notice]: Profile                                : main_10
vvenc [notice]: Level                                  : 4
vvenc [notice]: CU size                                : 128
vvenc [notice]: Max TB size                            : 64
vvenc [notice]: Min CB size                            : 4
vvenc [notice]: Motion search range                    : 384
vvenc [notice]: QP                                     : 33
vvenc [notice]: Max dQP signaling subdiv               : 2
vvenc [notice]: Cb QP Offset (dual tree)               : 0 (0)
vvenc [notice]: Cr QP Offset (dual tree)               : 0 (0)
vvenc [notice]: GOP size                               : 32
vvenc [notice]: PicReordering                          : 1
vvenc [notice]: Input bit depth                        : (Y:10, C:10)
vvenc [notice]: MSB-extended bit depth                 : (Y:10, C:10)
vvenc [notice]: Internal bit depth                     : (Y:10, C:10)
vvenc [notice]: cu_chroma_qp_offset_subdiv             : -1
vvenc [notice]: log2_sao_offset_scale_luma             : 0
vvenc [notice]: log2_sao_offset_scale_chroma           : 0
vvenc [notice]: Cost function                          : Lossy coding
vvenc [notice]: Film grain analysis                    : 0

Output #0, vvc, to 'output_vvenc.vvc':
  Metadata:
    encoder         : Lavf61.9.100
  Stream #0:0: Video: vvc, 1 reference frame, yuv420p10le(tv, progressive), 1920x1080, q=2-31, 6000 kb/s, 29.97 fps, 29.97 tbn
    Metadata:
      encoder         : Lavc61.24.100 libvvenc
[out#0/vvc @ 000001ce7f734000] Starting thread...
frame=    0 fps=0.0 q=0.0 size=       0KiB time=N/A bitrate=N/A speed=N/A
```
