### ISSUE TITLE
About multi-thread scalability

### ISSUE THREAD

**Issue by cyb70289** [fraunhoferhhi/vvenc#464]
Hi, thanks for this amazing software.
I have a quick question about multi-thread scalability. When I set `--Threads` to 8,16, or more, fps doesn't scale, it increases slow.
Very often the worker threads are waiting and with low CPU usage. Guess some work must be done in sequence.
I'm wondering if there are chances to improve multi-thread scalability.

**Comment by Jamaika1** [comment]
VVenc originally has auto thread and this isn't the maximum for given computer. (multithreading; -1: resolution < 720p: 4, < 5K 2880p: 8, >= 5K 2880p: 12 threads). MABS VVenc has max thread. https://www.mediafire.com/file/a4leabop1lldw97/vvenc_1.12.1-rc1-da540e6.7z/file
FFmpeg 7.1.0 with vvenc movie plays too fast. 
UVG266 isn't standard.
Mayby use pthread (for windows).
https://www.sendspace.com/file/h9c4z3

**Comment by lehmann-c** [comment]
Please have a look into our wiki, where the [Multi-Threading](https://github.com/fraunhoferhhi/vvenc/wiki/Encoder-Performance#multi-threading) approach is discussed.  
Beside this we cannot give any advise without knowing what you are doing.  
What is you setup? (HD,UHD) What platform are you running and what is your hardware?  
But the encoding speed won´t scale linear to the used threads in general.

**Comment by lehmann-c** [comment]
> VVenc originally has auto thread and this isn't the maximum for given computer. (multithreading; -1: resolution < 720p: 4, < 5K 2880p: 8, >= 5K 2880p: 12 threads). MABS VVenc has max thread. https://www.mediafire.com/file/a4leabop1lldw97/vvenc_1.12.1-rc1-da540e6.7z/file FFmpeg 7.1.0 with vvenc movie plays too fast. [Jamaika1/plugins_ffmpeg701_mingw1150@185b303](https://github.com/Jamaika1/plugins_ffmpeg701_mingw1150/commit/185b30335b0048e3e619b5d36b95c941cff38709) UVG266 isn't standard. Mayby use pthread (for windows). https://www.sendspace.com/file/h9c4z3

I´m not sure what your comments have to do with the question.
But ffmpeg (and also the [Media-autobuild-suite](https://github.com/m-ab-s/media-autobuild_suite) which is just a script framework to build ffmpeg for windows) is using the same threading as the vvenc applications and not max threads.
What do you mean with ffmpeg plays too fast and why are you referring to uvg266?

**Comment by cyb70289** [comment]
> Please have a look into our wiki, where the [Multi-Threading](https://github.com/fraunhoferhhi/vvenc/wiki/Encoder-Performance#multi-threading) approach is discussed. Beside this we cannot give any advise without knowing what you are doing. What is you setup? (HD,UHD) What platform are you running and what is your hardware? But the encoding speed won´t scale linear to the used threads in general.

Thanks for the info. I'm testing vvenc on AMD and Arm, with 1920x1080 stream, preset=medium. I observed very similar scaling line as the first picture shown in the wiki. And I did find enabling WPP improves scalability. I'm curious about scalability as Arm often performs better with more physical cores than x86, but the software must scale well to leverage this advantage.

**Comment by Jamaika1** [comment]
> But ffmpeg (and also the [Media-autobuild-suite](https://github.com/m-ab-s/media-autobuild_suite) which is just a script framework to build ffmpeg for windows) is using the same threading as the vvenc applications and not max threads.

My mistake. Decoder has max thread.
```
VVdeC, the Fraunhofer VVC/H.266 decoder, version 3.0.0 [THREADS=20; PARSE_DELAY=30; SIMD=AVX2]
```
> What do you mean with ffmpeg plays too fast and why are you referring to uvg266?

I provided examples in the link and played them in ffplay_vvc. And everything is clear.

**Comment by lehmann-c** [comment]
> > But ffmpeg (and also the [Media-autobuild-suite](https://github.com/m-ab-s/media-autobuild_suite) which is just a script framework to build ffmpeg for windows) is using the same threading as the vvenc applications and not max threads.
> 
> My mistake. Decoder has max thread.
> 
> ```
> VVdeC, the Fraunhofer VVC/H.266 decoder, version 3.0.0 [THREADS=20; PARSE_DELAY=30; SIMD=AVX2]
> ```
> 
> > What do you mean with ffmpeg plays too fast and why are you referring to uvg266?
> 
> I provided examples in the link and played them in ffplay_vvc. And everything is clear. https://forum.doom9.org/showthread.php?p=2009792#post2009792

The signalized framerate in the bitstream is correct.  It´s a playback issue of ffplay as you use raw bitstream (vvc).
When using an other player (like mpv) or when using a proper container (ISOBMFF/mp4 by using MP4Box) everything works properly.
Nevertheless that has nothing to do with this issue.
