### ISSUE TITLE
Wiki issue in Build section

### ISSUE THREAD

**Issue by patriceangot** [fraunhoferhhi/vvenc#466]
In the "Build using plain CMake" section of the wiki, the "install (locally)" seems not correct. Targets release-shared and release-static are mixed

install (locally):
cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
cmake --build build/release-shared -j
cmake --build build/release-static --target in

The correct commands should be the followings : 
install (locally):
cmake -S . -B build/release-static -DCMAKE_BUILD_TYPE=Release
cmake --build build/release-static -j
cmake --build build/release-static --target in

**Comment by lehmann-c** [comment]
Thanks for noticing!
The wiki has been updated.
