### ISSUE TITLE
YUV piping doesn't work

### ISSUE THREAD

**Issue by master-of-zen** [fraunhoferhhi/vvenc#47]
Example of command:
```
ffmpeg -hide_banner -i test.mkv -c:v rawvideo -pix_fmt  yuv420p10le - | ./vvencapp -p 1 --preset faster -o try.h266 --format yuv420_10 --size 1920x1080 --framerate 30 --qp 30 --qpa 0 --input "" -f 30
```
Output:
```
started @ Wed Apr  7 20:37:29 2021

vvencapp [error]: failed to open input file
```
related to this commit https://github.com/fraunhoferhhi/vvenc/commit/b465e4a148ace45fca007f9b927215fc4856ee49

**Comment by BlueSwordM** [comment]
I'm getting the same issue here.

`ffmpeg -hide_banner -i test.mkv -c:v rawvideo -pix_fmt  yuv420p10le - | ./vvencapp -p 1 --preset medium -o try.h266 --format yuv420_10 --size 1920x1080 --framerate 60 --qp 30 --qpa 0 --input "" -f 60`

`started @ Thusday Apr  8 13:47:49 2021

vvencapp [error]: failed to open input file
`

**Comment by adamjw24** [comment]
What do you think is the issue here? FFmpeg takes too long to produce input - it would be available only after the check on the vvenc side? In this case we do should add some explicit signaling of stdin-input ( -i - or -i stdin)

**Comment by Orum** [comment]
Using `-` to denote stdin would certainly be an improvement over the null string, as it's commonly used elsewhere (while null strings are not).

**Comment by baxxtor** [comment]
On linux, as stated above, vvenc fails to find the YUV input via stdin.  However, using the same command within Windows, vvenc will read the first frame or two then stops with FFMPEG broken pipe error.
