### ISSUE TITLE
building ffmpeg with libvvenc: pkg-config cannot find libvvenc with master

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [fraunhoferhhi/vvenc#483]
When configuring ffmpeg with libvvenc enabled with both ffmpeg master and vvenc master gets the following error:
ERROR: libvvenc >= 1.6.1 not found using pkg-config

manually running
pkg-config --modversion libvvenc
yields the following:
"1.12.1-rc1"

I suspect pgk-config gets confused because of the "rc1" suffix of the version.
Is there anything one can do about that?
(Note: this was not the case a few months ago when I last built ffmpeg with libvvenc)

**Comment by K-os** [comment]
Which platform are you building on and which ffmpeg version are you using?

I just built ffmpeg successfully in a clean debian:stable container. I first installed the ffmpeg prerequisites listed in the [ffmpeg wiki](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu#GettheDependencies) plus `libxml2-dev` and `nasm`. Then I followed the instructions from [our wiki](https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration#linux) and it compiled just fine.

These are the exact revisions I used:
vvenc: both 3065b1348 and 632e4b17d with today's update
ffmpeg: 018ec4fe

**Comment by AlexanderSchuetz97** [comment]
I am building on alpine linux and ffmpeg master.
I am linking everything statically against libc-musl.

The dockerfile used to compile is this:
```
FROM alpine:latest
RUN apk add nasm git alpine-sdk bash cmake ninja meson perl autoconf automake libtool gperf xz libogg yasm diffutils gawk linux-headers asciidoc doxygen xmlto gtest clang
```
The script I run inside the docker container is the following:
[compile.sh.zip](https://github.com/user-attachments/files/18038616/compile.sh.zip)
For some reason github force me to zip it before uploading.

As mentioned before the only line I need to comment out for the build to succeed is this:
git checkout c305325e7a7e22f337f3abd03e43508a42ae87b7

Maybe its because Its a static build? I do not see anything else I am doing different from what you describe.

I sadly cannot upload the other archive files described inside the script because they are too big and hit github's file limit.
If you require them then suggest a file sharing tool for me to upload the entire thing.

**Comment by AlexanderSchuetz97** [comment]
The configuring of ffmpeg itself fails.
The error is exactly:
ERROR: libvvenc >= 1.6.1 not found using pkg-config

**Comment by AlexanderSchuetz97** [comment]
FYI this information may be of use to you. now its 1.13.0-rc1 (this was not the case yesterday)
![image](https://github.com/user-attachments/assets/e1b0c601-1006-4ef6-9a11-d61d9255cda5)

**Comment by K-os** [comment]
The problem is that `-lgcc_s` is listed in `Libs.private` in `libvvenc.pc`. This library has no static version. We there is a similar issue in vvdec.

I'll create a PR to remove that. The workaround for now is to build VVenC with `-DCMAKE_CXX_FLAGS=-static-libgcc`.

By the way, the FFmpeg error log tells you what the actual problem is in `ffbuild/config.log`. The error messages printed by the ffmpeg configure-script are quite misleading, because it also tells you a dependency was missing, when it was actually found, but the test if it can be linked failed.

**Comment by AlexanderSchuetz97** [comment]
Well, my bad for not looking in the log of the configure script. 
It should have been a obvieus thing to look at...

I can confirm that adding 
-DCMAKE_CXX_FLAGS=-static-libgcc
to my cmake command will result in head building just ffmpeg+vvenc. 
Ill will task my CI to build the full version with all modules overnight with this option since doing so takes about 1 hour. Hopefully it will work now.

As a sidenote in the meantime I have through bruteforcing back commits more or less one by one found out that the last commit where it worked was "ab3733e38c8847564145a1ba183797f6d7c55db2"
The first commit where it didn't work was "18af3bb794e2b7fbf48cc066eb6d6a00654202d9"

I dont know if this info is useful for you, perhaps you can list this info somewhere in case someone tries to statically build anything inbetween? I did not check if you have any release inbetween head and those commits. Certainly your RC-Release from today is affected by this.

Anyways thank you very much for your help! 
Have a good weekend!
