### ISSUE TITLE
result video looks wrong and frame number doubled after enc and dec

### ISSUE THREAD

**Issue by dwindy** [fraunhoferhhi/vvenc#484]
Hello there,

I'm using the VVenc command 
`./vvencapp -i ../../examples/SOCCER_176x144_15_orig_02.yuv --preset slow -s 176x164 -r 15 -o soccer.266`
to encode a short video. 
Then, decode it with
`./vvdecapp -b ../../../vvenc/bin/release-static/soccer.266 -o soccer-raw.yuv`
and play the video with YUView.
The original video is all fine, as it looks like
![image](https://github.com/user-attachments/assets/92630c3f-7dcf-4270-b042-85ca19afac77)
However, the decoded video looks wrong, as it looks like
![image](https://github.com/user-attachments/assets/1957efac-7091-49cc-9b38-84dac5bb6653)

In the left info panel, it seems the Num Frames were doubled from 150 to 298 as well as the Nr Bytes doubled from 5702400 to 11343552.

I'm not sure whether the problem comes from VVenc or VVdec.

Thanks in advance

**Comment by K-os** [comment]
Switch the YUV Format in YUView to "YUV 4:2:0 10-bit LE" then it should look correct.

**Comment by adamjw24** [comment]
See https://github.com/fraunhoferhhi/vvenc/issues/26

**Comment by dwindy** [comment]
> Switch the YUV Format in YUView to "YUV 4:2:0 10-bit LE" then it should look correct.

Yes, I checked all the raw file properties and eventually found the 10-bit LE works.
It seems like the default output of VVenc is YUV420-10?

Thank you

**Comment by dwindy** [comment]
> The output of VVenC is VVC annexB bitstream ;)
> 
> But yes, per default that bitstreams has a bitdepth of 10.

Yes Adam, just checked issue 26 above, got the answers
Thank you
