### ISSUE TITLE
YUV Piping using stdin does not work under Windows

### ISSUE THREAD

**Issue by baxxtor** [fraunhoferhhi/vvenc#51]
Using the following command line, I am able to have vvenc read from stdin under Centos

ffmpeg -i 1.mp4 -c:v rawvideo -pix_fmt yuv420p -an -f rawvideo pipe:1 | vvencapp.exe -i - -o test.266 -s 1920x1080 -r 25 --preset=faster -q 25 

The exact same command under windows, vvenc reads and compresses a few frames from stdin then abruptly stops

**Comment by 1480c1** [comment]
As a first question, what shell are you running this with?

**Comment by baxxtor** [comment]
I am using BASH shell on Centos which works without issue.  On Windows, I am using the command (cmd) shell.

**Comment by baxxtor** [comment]
For me the issue has been fixed.  YUV piping via Stdin is working without issue now on Windows.  Thank You.

Would it be possible to apply the same / similar fix to vvdec?

**Comment by adamjw24** [comment]
Does the resulting bitstream look alright though? We really are heaving some issues with that.

An analogue patch for the vvdec is also coming.

**Comment by baxxtor** [comment]
Yes, I used vvdec to decode the encoded bitstream output to YUV and it plays back perfectly.  So far its working great.

**Comment by adamjw24** [comment]
Seems fixed for Windows. Problems reported under PowerShell, but works with cmd.exe.

**Comment by 1480c1** [comment]
> Seems fixed for Windows. Problems reported under PowerShell, but works with cmd.exe.

for powershell, it's probably because powershell by design tries to consume the entire stdout and runs a `\n` to `\r\n` conversion then pipes it to stdin for the next command (`>` is actually shorthand for `| Out-File` a lot of times)

https://github.com/PowerShell/PowerShell/issues/2145
