### ISSUE TITLE
Problems with high bitdepth

### ISSUE THREAD

**Issue by PhaseSpaceContinuum** [fraunhoferhhi/vvenc#60]
Issues similar to:
https://github.com/fraunhoferhhi/vvenc/issues/46?_pjax=%23js-repo-pjax-container

are encountered when setting 
122 #define RExt__HIGH_BIT_DEPTH_SUPPORT = 1

which causes

`/tmp/VVC_VVCenc/source/Lib/CommonLib/Buffer.cpp:358:3: error: ‘removeHighFreq8’ was not declared in this scope
   removeHighFreq8   = removeHighFreq;
   ^~~~~~~~~~~~~~~
/tmp/VVC_VVCenc/source/Lib/CommonLib/Buffer.cpp:358:3: note: suggested alternative: ‘removeHighFreq’
   removeHighFreq8   = removeHighFreq;
   ^~~~~~~~~~~~~~~
   removeHighFreq
/tmp/VVC_VVCenc/source/Lib/CommonLib/Buffer.cpp:359:3: error: ‘removeHighFreq4’ was not declared in this scope
   removeHighFreq4   = removeHighFreq;
   ^~~~~~~~~~~~~~~
/tmp/VVC_VVCenc/source/Lib/CommonLib/Buffer.cpp:359:3: note: suggested alternative: ‘removeHighFreq’
   removeHighFreq4   = removeHighFreq;
`
(see attached log for full output [log.txt](https://github.com/fraunhoferhhi/vvenc/files/6441871/log.txt))

which can only be partially resolved by setting

142 #define ENABLE_SIMD_OPT_BCW = 0
.

**Comment by adamjw24** [comment]
Encoding of 10-bit depth and HDR content is possible without changing compile-time options.
