### ISSUE TITLE
Enable ESD (--ESD 1) will cause crash.

### ISSUE THREAD

**Issue by 9reyson** [fraunhoferhhi/vvenc#63]
command:
--ESD 1 --preset medium -t 8 -qpa 0 --MaxParallelFrames 4 --WppBitEqual 1 -s 832x480 -fr 30 -f 33 -ip 32 --qp 30 -b str.bin -o rec.yuv -i E:\Seqs\RaceHorses_832x480_30.yuv

**Comment by adamjw24** [comment]
The options has not been tested and is not supported for now. The software was started based on VTM, which was build from HM, from which I believe this option initially origins.

We plan to go through all of the options and see if they work and have any desirable functionality, might take a while though.

Thanks for reporting.

**Comment by 9reyson** [comment]
Thanks a lot for your answer!
