### ISSUE TITLE
Files missing BOM cause errors on windows

### ISSUE THREAD

**Issue by YUKI2eN3e** [fraunhoferhhi/vvenc#71]
The files:
source\Lib\CommonLib\ProfileLevelTier.cpp
source\Lib\EncoderLib\EncHRD.cpp
both trigger warning C4819, switching them to UTF-8-BOM stops the warning.

**Comment by adamjw24** [comment]
Thanks for the report, we'll have a look.

**Comment by adamjw24** [comment]
We use UTF-8 without BOM throughout the code, so I'd rather stick to that. I found and fixed the actual problematic characters. Could you check if this resolved your problem?

**Comment by YUKI2eN3e** [comment]
Thanks you.
It seems to work fine now.
