### ISSUE TITLE
how to config lowdelayP(IPPP)

### ISSUE THREAD

**Issue by soaringleefighting** [fraunhoferhhi/vvenc#73]
Current default configure is random access. But I need low delay P.

**Comment by adamjw24** [comment]
There is low delay B configured in the cfg/experimental directory (its IBBBBBBB). You can adapt it to produce P frames only. You can also copy over the old 4-frame LDP pseudo GOP configuration from VTM, VVenC understands the semantics.

Still, to run LD or AI configs with VVenC, you need to use the expert encoder and please mind that the configurations are experimental and not officially supported as of now.

**Comment by soaringleefighting** [comment]
Thanks a lot. I modified cfg/experimental/lowdelay_fast.cfg and it works for me.
