### ISSUE TITLE
Supported dimensions

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#75]
Hi,
I'm writing a script to convert to any image / video to VVC. Is there any constraint for the media dimensions - like be multiple of 16 pixels or fixed supported resolutions?

**Comment by adamjw24** [comment]
There should be no restrictions. The encoder will internally pad the video and create appropriate signaling so that the decoder knows to only reconstruct the input dimensions.

Let us know if you find a dimensions that don't work.

**Comment by rafael2k** [comment]
Thanks Adam!
