### ISSUE TITLE
A question about v1.1.0

### ISSUE THREAD

**Issue by soaringleefighting** [fraunhoferhhi/vvenc#81]
Hi, yesterday I test the newest verison(v1.1.0) for random access and lowdelay P, vvenc v1.1 indeed speedup than v1.0 for random access configuration, but it still cost much time for lowdelay P. 
According to my experiments, vvenc v1.1(faster) vs. x264(veryfast), BD-rate decrease 59%, but time cost increases 8100%。

**Comment by soaringleefighting** [comment]
@adamjw24  Add on thing, random access configuration using vvencapp, but lowdelay P configuration using vvencFFapp.

**Comment by adamjw24** [comment]
So what is the question?

The BD-rate decrease you report if for lowdelay or for random-access? We only test vs x265, and only vs slow/slower/veryslow/placebo. What content and resolution is this for?

**Comment by soaringleefighting** [comment]
1. Test sequences is from CTC of HEVC，about 16 videos covering resolutions from 4K to 416x240.
2. The BD-rate decrease is for random-access(v1.1.0 vs v1.0.0).
3. My question is that speed up for lowdelay is not obvious. I doubt this.

**Comment by soaringleefighting** [comment]
Maybe I describe unclear. No matter for random-access or lowdelay, BD-rate decrease vs x264( or x265). I focus on the complexity of vvenc.

**Comment by adamjw24** [comment]
The low-delay config is experimental. We do not officially support it, or test it before each release. So its possible the speedup is less. I'm surprised it doesn't show between v1.0 and v1.1 tho, since its not specific for RA tools.

Thanks for checking.

**Comment by soaringleefighting** [comment]
Thanks adam.
