### ISSUE TITLE
VMAF for VVC

### ISSUE THREAD

**Issue by andini2807** [fraunhoferhhi/vvenc#87]
Hi, my name is Antonio and I am doing a final Master thesis. I need to get the VMAF value of an VVC video stream. How I can do it? Thank you.

**Comment by alexander-g2** [comment]
VVenC doesn't report VMAF scores. Use [VVdeC](https://github.com/fraunhoferhhi/vvdec) for decoding, and [VMAF](https://github.com/Netflix/vmaf) for measuring quality.

Encoding:
`vvencapp -s 640x360 -r 60 -c yuv420_10 -o VVC.266 -i source.yuv`

Decoding:
`vvdecapp -b VVC.266 -o VVC.yuv`

Measuring quality:
`vmaf -r source.yuv -d VVC.yuv -w 640 -h 360 -p 420 -b 10`
