### ISSUE TITLE
Possible unsafe flag naming

### ISSUE THREAD

**Issue by MilosR-ID** [fraunhoferhhi/vvenc#9]
Hello,

I came across a possible misleading flag name used in the _Picture_ class, which is related with _isMctfFiltered_ flag. If I'm right, not all frames are truly filtered with MCTF? However, the flag is set to true even for those frames that are not filtered by MTCF, which may lead to wrong conclusions for the users that are not familiar with implementation details of MCTF. It's a bit unsafe to use the current name if you agree? Is it maybe better to change to something else or to add additional flag?

Milos

**Comment by adamjw24** [comment]
The flag is ok. It might be better called isMctfProcessed, but in the end it doesn't matter. It means the picture has been processed by MCTF, whatever MCTF decided to do to it. For the processing outside of MCTF only this information is relevant.

Only case I think this would be relevant is if someone was to reuse the information generated during filtering, as in would need to know if MCTF actually filtered it or not. We might change it sometime in the future, but without a specific timeline.

**Comment by MilosR-ID** [comment]
"Only case I think this would be relevant is if someone was to reuse the information generated during filtering, as in would need to know if MCTF actually filtered it or not. " -- that’s exactly what I was doing, and that led me to ask this question.

Anyhow, I appreciate your answer.

**Comment by adamjw24** [comment]
In that case you'd need both flags. Filtered and Processed. After a discussion, we'll change the naming in the next update.
