### ISSUE TITLE
Best settings for offline still image compression

### ISSUE THREAD

**Issue by rafael2k** [fraunhoferhhi/vvenc#92]
Hi all,
Is there a recommended setting for offline (don't need to be realtime) still image encoding?

**Comment by rafael2k** [comment]
Another question - for a 8-bit yuv 420p, does it make sense to use the default 10-bit depth, or better set to use 8-bit internal depth?

**Comment by alexander-g2** [comment]
I would recommend leaving --internal-bitdepth 10. 10-bit can help to mitigate banding artifacts. And AFAIK, unlike with other encoders, encoding to 8-bit does not speed up encoding since VVenC has no assembly for 8-bit.

**Comment by rafael2k** [comment]
Right, so I'll stick with 10-bit and then convert back to 8-bit after decoding.

**Comment by rafael2k** [comment]
Btw, any chance the 8-bit code path will receive SIMD optimized code?

**Comment by adamjw24** [comment]
Not in the near future. This would mean rewriting a lot of code and vastly complicating the buffer pointer logic we use. All of this while we do support the use 8-bit coding, just with a suboptimal runtime.

**Comment by adamjw24** [comment]
I think this issue is so far resolved, closing.
